export const MEDITATION_FILTERS = [
    { id: 'sleep', name: 'Better Sleep', emoji: '🌙', color: '#6366f1' },
    { id: 'morning', name: 'Morning Boost', emoji: '☀️', color: '#f59e0b' },
    { id: 'focus', name: 'Focus', emoji: '🎯', color: '#3b82f6' },
    { id: 'self-love', name: 'Self-Love', emoji: '💗', color: '#ec4899' },
    { id: 'anxiety', name: 'Anxiety Relief', emoji: '🛡️', color: '#10b981' },
    { id: 'sovereignty', name: 'Sovereignty & Power', emoji: '👑', color: '#b45309' },
    { id: 'strategic-mindset', name: 'Strategic Mindset', emoji: '🧠', color: '#7c3aed' },
    { id: 'breathwork', name: 'Breathwork', emoji: '💨', color: '#0d9488' },
    { id: 'biohacking', name: 'Biohacking', emoji: '🧬', color: '#14b8a6' },
    { id: 'stoicism', name: 'Stoicism', emoji: '🏛️', color: '#64748b' },
    { id: 'psychology', name: 'Psychology', emoji: '💡', color: '#8b5cf6' },
    { id: 'charisma', name: 'Charisma', emoji: '🗣️', color: '#f43f5e' },
    { id: 'modern-man', name: 'Modern Man', emoji: '👔', color: '#1e293b' },
    { id: 'modern-woman', name: 'Modern Woman', emoji: '👗', color: '#d946ef' },
    { id: 'shadow-work', name: 'Shadow Work', emoji: '🌑', color: '#334155' },
    { id: 'frame-control', name: 'Frame Control', emoji: '🔳', color: '#0ea5e9' },
    { id: 'machiavelli', name: 'Machiavelli', emoji: '📜', color: '#9f1239' },
    { id: 'dark-psychology', name: 'Dark Psychology', emoji: '🖤', color: '#0f172a' },
    { id: 'weight-loss', name: 'Weight Loss', emoji: '⚖️', color: '#84cc16' },
    { id: 'muscle', name: 'Muscle Builder', emoji: '💪', color: '#ef4444' },
];
