
const fs = require('fs');
const path = 'c:/Users/jwfca/Desktop/BluomAppNew/locales/pt/translation.json';
const content = fs.readFileSync(path, 'utf8');
const data = JSON.parse(content);

data.wellness = {
  "title": "Bem-estar",
  "subtitle": "Saúde mental e otimização",
  "sleep": "Sono",
  "lastNight": "Ontem à noite",
  "mood": "Humor",
  "notLogged": "Não registado",
  "moods": {
    "great": "Ótimo",
    "good": "Bom",
    "okay": "Normal",
    "meh": "Mais ou menos",
    "bad": "Mau",
    "struggling": "Com dificuldades"
  },
  "habitsLabel": "Hábitos",
  "doneToday": "Concluído hoje",
  "meditation": "Meditação",
  "thisWeek": "Esta semana",
  "quickLog": "Registo Rápido",
  "trackDaily": "Acompanha o teu bem-estar diário",
  "meditate": "Meditar",
  "insights": "Estatísticas",
  "proBannerBadge": "✦ PRO · Com IA · Renova Mensalmente",
  "freeBannerBadge": "Plano de 28 Dias · Gratuito",
  "proBannerTitle": "O Teu Plano Mental\nPersonalizado",
  "freeBannerTitle": "O Teu Plano de\nSaúde Mental",
  "proPlanTailored": "Plano de IA adaptado ao teu stress, sono e objetivos — renova a cada 30 dias",
  "freeUsers28DaysSub": "Utilizadores gratuitos recebem um plano de 28 dias. Quando terminar, atualiza para Pro para continuar.",
  "viewPlan": "Ver plano →",
  "wellnessHubs": "Hubs de Bem-estar",
  "mentalToolbox": "A tua caixa de ferramentas mental",
  "reflectionsLabel": "Reflexões",
  "journalGratitude": "Diário e gratidão",
  "brainGames": "Jogos Mentais",
  "sharpenMind": "Afia a tua mente",
  "dailyStreaks": "Sequências diárias",
  "lifeGoals": "Objetivos de Vida",
  "dreamAchieve": "Sonha e alcança",
  "libraryLabel": "Biblioteca",
  "curatedKnowledge": "Conhecimento curado",
  "moodTrend": "Tendência de Humor (7 dias)",
  "analyticsTitle": "Análise de Bem-estar",
  "mentalHealth": {
    "badgePro": "✦ PRO · Com IA · Renova Mensalmente",
    "badgeFree": "Plano de 28 Dias · Gratuito",
    "heroTitle1": "Plano de",
    "heroTitle2": "Saúde Mental",
    "heroSubPro": "Personalizado de acordo com os teus padrões de stress, dados de sono e objetivos.",
    "heroSubFree": "Um programa de 28 dias baseado em evidências. Utilizadores gratuitos recebem um plano completo. Atualiza para Pro para continuar.",
    "progressText": "Dia {{day}} de 28 completo · {{pct}}%",
    "todayLabel": "HOJE · DIA {{day}}",
    "start": "Começar",
    "pillarBalance": "Equilíbrio de Pilares",
    "pillarSub": "Atividades concluídas em cada dimensão",
    "overview": "Visão Geral de 4 Semanas",
    "weekLabel": "SEMANA {{week}}",
    "continueJourney": "Continua a Tua Jornada",
    "freeUsers28DaysFull": "Utilizadores gratuitos recebem um plano de 28 dias. Quando os teus 28 dias terminarem, atualiza para Pro para continuares a tua transformação com um plano gerado por IA — renovado mensalmente.",
    "goPro": "Atualizar para Pro →",
    "disclaimer": "Este programa baseia-se em práticas baseadas em evidências de TCC, ACT, psicologia positiva, neurociência e terapia somática. Não substitui os cuidados de saúde mental profissionais.",
    "dayLabel": "DIA {{day}}",
    "todaysPractices": "Práticas de Hoje",
    "eveningReflection": "📝 Reflexão Noturna",
    "durationMin": "{{min}} min",
    "evening": "Noite",
    "themes": {
      "w1Title": "Fundação",
      "w1Tagline": "Constrói a tua base",
      "w2Title": "Resiliência",
      "w2Tagline": "Fortalece a mente sob pressão",
      "w3Title": "Crescimento",
      "w3Tagline": "Expande além da zona de conforto",
      "w4Title": "Integração",
      "w4Tagline": "Torna-o parte de quem és"
    },
    "pillars": {
      "mind": "Mente",
      "body": "Corpo",
      "connection": "Conexão",
      "purpose": "Propósito"
    },
    "intensity": {
      "light": "Leve",
      "moderate": "Moderado",
      "deep": "Profundo"
    },
    "days": {
      "d1Title": "Chegar Aqui",
      "d1Focus": "Enraizamento",
      "d1Affirm": "Estou exatamente onde preciso de estar.",
      "d1Reflect": "Qual é a coisa que te traz paz neste momento?",
      "d2Title": "Varrimento Corporal",
      "d2Focus": "Consciência",
      "d2Affirm": "Ouço o que o meu corpo me diz.",
      "d2Reflect": "Onde sentes tensão hoje? Por que poderá ser?",
      "d3Title": "Conectar",
      "d3Focus": "Relacionamentos",
      "d3Affirm": "Dou e recebo apoio livremente.",
      "d3Reflect": "Quem na tua vida te eleva? Quando lhe disseste pela última vez?",
      "d4Title": "Descansar e Integrar",
      "d4Focus": "Recuperação",
      "d4Affirm": "O descanso é produtivo. Honro a minha necessidade de quietude.",
      "d4Reflect": "O que drena a tua energia? O que a restaura?",
      "d5Title": "Coragem",
      "d5Focus": "Autoexpressão",
      "d5Affirm": "A minha voz importa. Expresso-me com confiança.",
      "d5Reflect": "O que dirias se o medo não estivesse no caminho?",
      "d6Title": "Check-in de Valores",
      "d6Focus": "Propósito",
      "d6Affirm": "Vivo em alinhamento com o que é mais importante para mim.",
      "d6Reflect": "Nomeia os teus 3 principais valores. A tua semana refletiu-os?",
      "d7Title": "Celebrar Semana 1",
      "d7Focus": "Reflexão e Recompensa",
      "d7Affirm": "Reconheço cada passo que dou em direção ao meu bem-estar.",
      "d7Reflect": "Qual foi a tua maior vitória esta semana — por mais pequena que seja?",
      "d8Title": "Auditoria de Stress",
      "d8Focus": "Stress",
      "d8Affirm": "Consigo lidar com coisas difíceis.",
      "d8Reflect": "O que mais te stressa agora? É urgente, importante, ambos ou nenhum?",
      "d9Title": "Reenquadramento",
      "d9Focus": "Cognição",
      "d9Affirm": "Escolho como interpreto o meu mundo.",
      "d9Reflect": "Pega num pensamento stressante. Qual é outra forma de o ver?",
      "d10Title": "Rotulagem Emocional",
      "d10Focus": "Emoções",
      "d10Affirm": "Os meus sentimentos são mensageiros válidos.",
      "d10Reflect": "Que emoção tens evitado? O que poderá estar a tentar dizer-te?",
      "d11Title": "Limites",
      "d11Focus": "Limites",
      "d11Affirm": "O meu 'não' é um ato de autorrespeito.",
      "d11Reflect": "Onde na tua vida precisas de um limite mais firme?",
      "d12Title": "Autocompaixão",
      "d12Focus": "Eu",
      "d12Affirm": "Trato-me com a bondade que dou aos outros.",
      "d12Reflect": "O que dirias a um amigo que estivesse a passar pelo que tu estás a enfrentar?",
      "d13Title": "Bateria Social",
      "d13Focus": "Energia",
      "d13Affirm": "Protejo a minha energia sem culpa.",
      "d13Reflect": "Quais relacionamentos te dão energia? Quais a esgotam?",
      "d14Title": "Reflexão Semana 2",
      "d14Focus": "Revisão",
      "d14Affirm": "O crescimento leva tempo. Sou paciente comigo mesmo.",
      "d14Reflect": "Como cresceste desde o Dia 1?",
      "d15Title": "Curiosidade",
      "d15Focus": "Aprendizagem",
      "d15Affirm": "A curiosidade é o meu superpoder.",
      "d15Reflect": "Que tópico sempre quiseste aprender mas continuaste a adiar?",
      "d16Title": "Escada do Medo",
      "d16Focus": "Coragem",
      "d16Affirm": "Caminho em direção ao que me assusta — um passo de cada vez.",
      "d16Reflect": "Qual é a pequena coisa que tens evitado devido ao medo?",
      "d17Title": "Estado de Flow",
      "d17Focus": "Engajamento",
      "d17Affirm": "Quando perco a noção do tempo, é quando estou mais vivo.",
      "d17Reflect": "Quando estiveste pela última vez completamente absorvido em algo? O que estavas a fazer?",
      "d18Title": "Auditoria de Significado",
      "d18Focus": "Propósito",
      "d18Affirm": "A minha vida faz sentido porque eu escolho que assim seja.",
      "d18Reflect": "O que faria a tua vida sentir-se mais significativa?",
      "d19Title": "Pontos Fortes",
      "d19Focus": "Identidade",
      "d19Affirm": "Os meus pontos fortes são dons únicos que ofereço ao mundo.",
      "d19Reflect": "Em que és naturalmente bom que os outros costumam notar?",
      "d20Title": "Perdão",
      "d20Focus": "Libertação",
      "d20Affirm": "O perdão é um presente que dou a mim mesmo.",
      "d20Reflect": "Por quem ou pelo que guardas ressentimento? Como seria libertá-lo?",
      "d21Title": "Revisão Semana 3",
      "d21Focus": "Reflexão",
      "d21Affirm": "Não sou quem era. Estou a tornar-me em quem quero ser.",
      "d21Reflect": "O que te surpreendeu em ti na Semana 3?",
      "d22Title": "Empilhamento de Hábitos",
      "d22Focus": "Sistemas",
      "d22Affirm": "As minhas rotinas são a arquitetura do meu melhor eu.",
      "d22Reflect": "Quais as 3 práticas deste programa que queres manter para sempre?",
      "d23Title": "Mudança de Identidade",
      "d23Focus": "Identidade",
      "d23Affirm": "Sou a pessoa que escolhi tornar-me.",
      "d23Reflect": "Escreve a tua nova declaração de identidade: 'Sou alguém que ____.'",
      "d24Title": "Sistema de Apoio",
      "d24Focus": "Comunidade",
      "d24Affirm": "Estou rodeado de pessoas que querem que eu prospere.",
      "d24Reflect": "Quem na tua vida apoia a tua jornada de saúde mental?",
      "d25Title": "Eu Futuro",
      "d25Focus": "Visão",
      "d25Affirm": "O meu eu futuro vale o investimento de hoje.",
      "d25Reflect": "Escreve uma carta do teu eu futuro daqui a um ano.",
      "d26Title": "Plano de Manutenção",
      "d26Focus": "Sustentabilidade",
      "d26Affirm": "Tenho as ferramentas. Escolho usá-las.",
      "d26Reflect": "O que farás quando as coisas ficarem difíceis novamente?",
      "d27Title": "Cerimónia de Gratidão",
      "d27Focus": "Gratidão",
      "d27Affirm": "Estou orgulhoso do trabalho que fiz.",
      "d27Reflect": "Do que estás mais orgulhoso este mês?",
      "d28Title": "Novo Começo",
      "d28Focus": "Continuidade",
      "d28Affirm": "Cada dia é um novo começo.",
      "d28Reflect": "Como será o próximo capítulo da tua vida?",
      "activities": {
        "d1a1Title": "Enraizamento 5-4-3-2-1",
        "d1a1Desc": "Nomeia 5 coisas que vês, 4 que podes tocar, 3 que ouves, 2 que cheiras, 1 que saboreias.",
        "d1a1Why": "Ativa o sistema nervoso parassimpático em 90 segundos.",
        "d1a2Title": "Respiração Quadrada (Box Breathing)",
        "d1a2Desc": "Inala 4s → Retém 4s → Expira 4s → Retém 4s. Repete 8 ciclos.",
        "d1a2Why": "Reduz o cortisol em até 25% (Stanford Neuroscience, 2023).",
        "d1a3Title": "Semente de Gratidão",
        "d1a3Desc": "Escreve 3 coisas muito específicas pelas quais estás grato hoje.",
        "d1a3Why": "A gratidão ativa o córtex pré-frontal medial, reduzindo a ansiedade."
      }
    }
  }
};

data.achievements = {
  "title": "Conquistas",
  "first_workout": {
    "title": "Primeiros Passos",
    "description": "Conclui o teu primeiro treino! 🎯"
  },
  "step_goal": {
    "title": "Mestre dos Passos",
    "description": "Alcança 1000+ passos num dia! 🚶"
  },
  "calorie_burner": {
    "title": "Queimador de Calorias",
    "description": "Queima 500+ calorias num dia! 🔥"
  },
  "workout_streak_3": {
    "title": "Sequência de 3 Dias",
    "description": "Treina durante 3 dias consecutivos! 💪"
  },
  "workout_warrior": {
    "title": "Guerreiro do Treino",
    "description": "Conclui 5 treinos num único dia! ⚔️"
  },
  "time_champion": {
    "title": "Campeão do Tempo",
    "description": "Exercita-te por 60+ minutos num dia! ⏰"
  },
  "week_warrior": {
    "title": "Guerreiro da Semana",
    "description": "Treina 5+ vezes esta semana! 🏆"
  },
  "variety_master": {
    "title": "Mestre da Variedade",
    "description": "Experimenta 3 tipos diferentes de treino! 🌈"
  }
};

fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
console.log('Success');
