const fs = require('fs');

const mensHealth = {
    "optimizationHub": "Hub de Otimização",
    "protocol": "Protocolo",
    "system": "Sistema",
    "today": "Hoje",
    "modeNatural": "Natural",
    "taglineNatural": "Testosterona Otimizada",
    "modeEnhanced": "Melhorado",
    "taglineEnhanced": "Inteligência de Ciclo",
    "modeAthlete": "Atleta",
    "taglineAthlete": "Modo Competição Ativo",
    "pillarSleep": "Sono",
    "pillarStress": "Stress",
    "pillarDrive": "Vitalidade",
    "pillarRecovery": "Recuperação",
    "pillarFocus": "Foco",
    "pillarActivity": "Atividade",
    "tipSleepLow": "Menos de 7h de sono reduz a testosterona até 15%. Prioriza 8h.",
    "tipSleepOk": "Sono otimizado para produção de testosterona.",
    "tipStressHigh": "Cortisol alto suprime diretamente a testosterona. Ashwagandha + meditação.",
    "tipStressOk": "Stress bem gerido.",
    "tipDriveLow": "Líbido baixa é sinal precoce de testosterona subótima ou prolactina elevada.",
    "tipDriveOk": "Níveis de vitalidade saudáveis.",
    "tipRecoveryLow": "Recuperação fraca eleva o cortisol e prejudica a síntese de testosterona. Verifica sono + zinco.",
    "tipRecoveryOk": "Recuperação a evoluir bem.",
    "tipFocusLow": "Clareza mental baixa está ligada a testosterona subótima e cortisol alto.",
    "tipFocusOk": "Função cognitiva saudável.",
    "tipActivity": "Treino de resistência 3–4x/semana é o mais eficaz para a testosterona com base em evidências.",
    "phaseOff": "Fora de Ciclo",
    "phaseOffDesc": "Produção hormonal natural a recuperar. Foca nos marcadores de saúde e otimização natural.",
    "phaseBlast": "Em Blast",
    "phaseBlastDesc": "Fase anabólica de pico. Maximiza o estímulo de treino, monitoriza a pressão arterial e marcadores de stress orgânico.",
    "phaseCruise": "Cruising",
    "phaseCruiseDesc": "Dose de manutenção. Ponte entre blasts. Monitoriza hematócrito e lipídeos regularmente.",
    "phasePCT": "PCT",
    "phasePCTDesc": "Terapia pós-ciclo. Reinicialização da HPTA em curso. Prioriza recuperação, sono e marcadores de saúde.",
    "quizHeroTitle": "Hub de Otimização Masculina",
    "quizHeroSub": "4 perguntas para construir o teu protocolo — desde otimização natural de testosterona até gestão de atletas avançados. Todos os dados são privados.",
    "alreadyLoaded": "✦ Já carregado do teu perfil",
    "articleDisclaimer": "Conteúdo educativo, não aconselhamento médico. Consulta sempre um médico para orientação personalizada.",
    "vitalityCheckin": "Registo de Vitalidade",
    "vitalitySub": "Avalia cada pilar honestamente. O teu T-Opt Score atualiza em tempo real.",
    "tOptScore": "PONTUAÇÃO T-OPT",
    "drivePillar": "Vitalidade / Líbido",
    "recoveryPillar": "Estado de Recuperação",
    "focusPillar": "Foco Mental",
    "sleepPillar": "Qualidade do Sono",
    "pillarDriveShort": "V",
    "pillarRecoveryShort": "R",
    "pillarFocusShort": "F",
    "systemOptimization": "Otimização do Sistema",
    "dailyProtocols": "Protocolos Diários",
    "performanceLib": "Biblioteca de Performance Masculina",
    "moodSynced": "Humor sincronizado do Wellness",
    "updateStatus": "Atualizar Estado do Sistema",
    "pelvicTitle": "Protocolo de Poder Pélvico",
    "pelvicSub": "Melhora a função erétil, controlo urinário, desempenho sexual e estabilidade do core.",
    "pelvicInstructions": "Contrai 5s → Relaxa 5s → Repete. 10–15 ciclos. Prática diária dá resultados em 4–6 semanas.",
    "startProtocol": "Iniciar Protocolo",
    "finishLog": "Terminar & Registar",
    "yourStack": "O Teu Stack",
    "unlockStack": "Desbloqueia o Teu Stack",
    "unlockStackSub": "Atualiza para Pro para veres recomendações personalizadas de acordo com os teus objetivos.",
    "suppCritical": "⚠️ Crítico",
    "suppCore": "✅ Stack Base",
    "suppOptional": "💡 Opcional",
    "suppLocked": "Personalização bloqueada para utilizadores gratuitos.",
    "logStack": "Registar Stack de Hoje",
    "suppDisclaimer": "Consulta sempre um médico antes de iniciar suplementos, especialmente se tomares medicação ou estiveres em ciclo.",
    "healthMarkers": "Marcadores de Saúde",
    "healthMarkersSub": "Regista os teus últimos valores de laboratório e leituras de pressão arterial. Acompanha tendências ao longo do tempo.",
    "normal": "Normal",
    "warning": "Alerta",
    "saveMarkers": "Guardar Marcadores",
    "peakWeekProtocol": "Protocolo de Semana Pico",
    "daysToShow": "Dias para mostrar",
    "peakDay7Title": "D-7: Última sessão pesada",
    "peakDay7Body": "Deplecionar glicogénio. Hidratos: 1,5g/kg. Sódio moderado. Ingestão de água normal.",
    "peakDay6Title": "D-6: Depleção continua",
    "peakDay6Body": "Low carb (1g/kg). Proteína alta. Começa a monitorizar a flutuação de peso diária.",
    "peakDay5Title": "D-5: Verificação muscular",
    "peakDay5Body": "Nota a plenitude e vascularidade muscular. Aumenta os hidratos se estiveres plano.",
    "peakDay4Title": "D-4: Iniciar carb load",
    "peakDay4Body": "Hidratos: 4–6g/kg. Fontes de baixo IG: batata-doce, arroz, aveia. Mantém gordura baixa.",
    "peakDay3Title": "D-3: Carb load máximo",
    "peakDay3Body": "Hidratos: 6–8g/kg. Atenção ao derrame (definição turva). Reduz se necessário.",
    "peakDay2Title": "D-2: Gestão de água",
    "peakDay2Body": "Reduz água ligeiramente (não eliminar). Aumenta alimentos com potássio. Última manipulação de sódio.",
    "peakDay1Title": "Dia do Espetáculo",
    "peakDay1Body": "Bebe água aos goles. Carrega hidratos nos bastidores (bolos de arroz + mel). Aquece 20 min antes do palco. Confia na tua preparação.",
    "carbLoadActive": "Carb load ativo",
    "tabToday": "Hoje",
    "tabTrack": "Análise",
    "tabInsights": "Insights",
    "tabLearn": "Aprender",
    "peakWeekTool": "Ferramenta Semana Pico",
    "openProtocol": "Abrir Protocolo",
    "pelvicActionSub": "Core, função erétil & urinária",
    "core": "base",
    "critical": "crítico",
    "sevenDayTrend": "Tendência de Vitalidade 7 Dias",
    "emptyTrack": "Regista a tua vitalidade diariamente para ver a tua tendência aqui.",
    "tOptPillars": "Pilares de Otimização de Testosterona",
    "cycleTracker": "Rastreador de Ciclo",
    "currentPhase": "Fase Atual",
    "week": "Semana",
    "of": "de",
    "healthMarkersMonitor": "Marcadores de Saúde a Monitorizar",
    "logMarkers": "Registar Marcadores de Saúde",
    "compPrep": "Preparação para Competição",
    "peakWeekSub": "Carb load dia a dia, manipulação de água e orientação para palco",
    "needsAttention": "precisa de atenção",
    "annualPanel": "Painel de sangue anual recomendado",
    "annualPanelBody": "Aos {{age}} anos, acompanhar testosterona total, testosterona livre, SHBG, estradiol e tiroide anualmente dá-te os dados para otimizar proativamente.",
    "fatLossTitle": "Perda de Gordura & Testosterona",
    "fatLossBody": "Restrição calórica agressiva abaixo de 15 kcal/kg/dia suprime a testosterona. Visa um défice máximo de 15–20%. Prioriza proteína 2,2g/kg para preservar músculo.",
    "progressiveTitle": "Protocolo de Sobrecarga Progressiva",
    "progressiveBody": "Aumenta o peso, repetições ou densidade em cada sessão. O treino pesado é o sinal anabólico primário.",
    "zincTitle": "A Importância do Zinco",
    "zincBody": "O zinco é um inibidor natural da aromatase. 30mg/dia ajudam a manter a testosterona e reduzir a conversão em estrogénio.",
    "cortisolTitle": "O Inimigo do Testo",
    "cortisolBody": "O cortisol alto é o antagonista direto da testosterona. Sono, meditação e ashwagandha são as tuas melhores defesas.",
    "markerPlaceholder": "Insere {{unit}}...",
    "personalisedInsights": "Insights Personalizados",
    "articles": {
        "tBlueprint": { "title": "O Blueprint da Testosterona", "category": "Hormonas", "body": "A testosterona atinge o pico entre as 6h e as 8h da manhã e é mais baixa à noite. O sono é a maior alavanca — uma semana de 5h de sono reduz a testosterona para níveis de castração em homens jovens. O protocolo: 8h de sono, treino de resistência 4x/semana, zinco 30mg, vitamina D3 5000IU e gestão de cortisol." },
        "sleepTesto": { "title": "Sono: O Anabólico Natural", "category": "Recuperação", "body": "A maior parte da produção de testosterona ocorre durante o sono REM profundo. Se dormes 5h ou menos, a tua testosterona livre desce drasticamente. Prioriza o quarto escuro, frio e sem ecrãs 1h antes de deitar." },
        "trainingMax": { "title": "Treino para Testosterona Máxima", "category": "Treino", "body": "Movimentos compostos pesados (agachamentos, pesos mortos, press) recrutam mais unidades motoras e provocam uma resposta hormonal maior do que exercícios de isolamento. Mantém o treino abaixo de 75 min para evitar o pico de cortisol." },
        "eatingTesto": { "title": "Nutrição para Otimização Hormonal", "category": "Nutrição", "body": "A testosterona é derivada do colesterol. Dietas de gordura ultra-baixa destroem a produção hormonal. Consome gorduras saudáveis (ovos, abacate, azeite) e mantém o zinco alto." },
        "cortisolEnemy": { "title": "Cortisol: O Assassino de Ganhos", "category": "Stress", "body": "O stress crónico mantém o cortisol elevado, o que inibe a hormona libertadora de gonadotrofinas (GnRH). Sem GnRH, os teus testículos não recebem o sinal para produzir testosterona." },
        "harmReduction": { "title": "Redução de Danos & Saúde Organica", "category": "Saúde", "body": "Se utilizas compostos, a monitorização da pressão arterial e hematócrito é inegociável. TUDCA e NAC são essenciais para a proteção hepática." },
        "peakWeek": { "title": "A Ciência da Semana Pico", "category": "Performance", "body": "A semana de pico não serve para ganhar músculo, mas para o mostrar. Manipulação de água e sódio combinada com carb loading estratégico cria o look 'seco e cheio'." },
        "bloodTests": { "title": "Ler as Tuas Análises ao Sangue", "category": "Ciência", "body": "Não olhes apenas para a Testosterona Total. A Testosterona Livre e o SHBG dizem quanto 'combustível' tens realmente disponível para as células." }
    },
    "markers": {
        "bp": { "label": "Pressão Arterial", "tip": "Verifica semanalmente. Crítico se estiveres em ciclo." },
        "hct": { "label": "Hematócrito", "tip": "HCT elevado aumenta o risco de coágulos. Monitoriza em cruise/blast." },
        "ldl": { "label": "Colesterol LDL", "tip": "Androgénios podem piorar o perfil lipídico. Foca em ómega-3." },
        "liver": { "label": "ALT (Fígado)", "tip": "Essencial para utilizadores de orais. NAC + TUDCA mandatórios." },
        "psa": { "label": "PSA (40+)", "tip": "Saúde da próstata. Rastreio anual para utilizadores enhanced." }
    }
};

const transPath = 'locales/pt/translation.json';
const transContent = JSON.parse(fs.readFileSync(transPath, 'utf8'));

transContent.mensHealth = mensHealth;

fs.writeFileSync(transPath, JSON.stringify(transContent, null, 2), 'utf8');
console.log('mensHealth translation updated with clean strings');
