/**
 * Disposable / temporary email domain blocklist.
 * Used in signup flow to prevent fake account creation.
 * Apple Private Relay (privaterelay.appleid.com) is intentionally NOT blocked —
 * it is a legitimate Apple privacy feature.
 */
const TEMP_EMAIL_DOMAINS = new Set([
  // ── Top offenders ───────────────────────────────────────────
  'mailinator.com', 'guerrillamail.com', 'guerrillamail.info', 'guerrillamail.net',
  'guerrillamail.org', 'guerrillamail.de', 'guerrillamail.biz',
  'yopmail.com', 'yopmail.fr', 'yopmail.net',
  'throwam.com', 'throwam.net', 'trashmail.com', 'trashmail.net',
  'trashmail.me', 'trashmail.at', 'trashmail.io', 'trashmail.org',
  'sharklasers.com', 'guerrillamailblock.com', 'grr.la', 'guerrillamail.info',
  'spam4.me', 'spamgourmet.com', 'spamgourmet.net', 'spamgourmet.org',
  'spamgourmet.com', 'spamgourmet.net',
  'mailnull.com', 'mailnull.net',
  'spamcorps.com', 'spam.la', 'spamspot.com',
  // ── 10 minute mail variants ──────────────────────────────────
  '10minutemail.com', '10minutemail.net', '10minutemail.org',
  '10minutemail.de', '10minutemail.co.uk',
  'tempmail.com', 'tempmail.net', 'tempmail.org', 'tempmail.de',
  'temp-mail.org', 'temp-mail.io', 'temp-mail.ru',
  'dispostable.com', 'dispostable.net',
  'mailtemp.info', 'mailtemp.net',
  'fakeinbox.com', 'fakeinbox.net',
  'mailnesia.com', 'mailnesia.net',
  'maildrop.cc', 'maildrop.net',
  'throwam.com',
  // ── Disposable services ──────────────────────────────────────
  'getairmail.com', 'getairmail.net',
  'mailbucket.org', 'mailbucket.net',
  'mailsac.com', 'mailsac.net',
  'discard.email', 'discard.org',
  'discardmail.com', 'discardmail.de',
  'throwaway.email', 'throwaway.net',
  'throwam.com', 'throwam.net',
  'getnada.com', 'nada.email', 'nada.ltd',
  'mohmal.com', 'mohmal.im',
  'emkei.cz',
  'tempr.email', 'tempail.com',
  'fleckens.hu',
  'spamfree24.org', 'spamfree24.de',
  'meltmail.com',
  'safetymail.info',
  'mailcatch.com',
  'spamevader.com', 'spaml.com', 'spaml.de',
  'jetable.fr.nf', 'jetable.net', 'jetable.org',
  'nomail.xl.cx', 'nomail.pw',
  'binkmail.com',
  'mt2015.com', 'mt2014.com', 'mt2016.com',
  'deadaddress.com',
  'despammed.com',
  'filzmail.com',
  'grandmamail.com',
  'hushmail.com',
  'ieatspam.eu', 'ieatspam.info',
  'incognitomail.com', 'incognitomail.net', 'incognitomail.org',
  'instantemailaddress.com',
  'kasmail.com',
  'klzlk.com',
  'letthemeatspam.com',
  'lol.ovpn.to',
  'lookugly.com',
  'lortemail.dk',
  'mailbidon.com',
  'mailblocks.com',
  'mailbolt.com',
  'mailchop.com',
  'mailexpire.com',
  'mailfa.tk',
  'mailforspam.com',
  'mailfreeonline.com',
  'mailguard.me',
  'mailhazard.com', 'mailhazard.us',
  'mailimate.com',
  'mailme.lv',
  'mailnew.com',
  'mailnobody.com',
  'mailpick.biz',
  'mailproxsy.com',
  'mailrock.biz',
  'mailscrap.com',
  'mailseal.de',
  'mailshell.com',
  'mailsiphon.com',
  'mailslapping.com',
  'mailslite.com',
  'mailsource.info',
  'mailsucker.net',
  'mailtemp.net',
  'mailtome.de',
  'mailtothis.com',
  'mailtrash.net',
  'mailtv.net', 'mailtv.tv',
  'mailup.net',
  'mailwithyou.com',
  'malahov.de',
  'manifestgenerator.com',
  'mbx.cc',
  'mega.zik.dj',
  'meltmail.com',
  'mierdamail.com',
  'mintemail.com',
  'misterpinball.de',
  'myTrashMail.com',
  'mychurch.com',
  'nocmail.com',
  'noicd.com',
  'nomorespamemails.com',
  'nonspam.eu',
  'nonspammer.de',
  'noref.in',
  'nospam.ze.tc',
  'nospam4.us',
  'nospamfor.us',
  'nospammail.net',
  'notmailinator.com',
  'nwldx.com',
  'objectmail.com',
  'obobbo.com',
  'odnorazovoe.ru',
  'oneoffemail.com',
  'onewaymail.com',
  'oopi.org',
  'ott.to',
  'owlpic.com',
  'pancakemail.com',
  'payspade.com',
  'pjjkp.com',
  'plexolan.de',
  'poczta.onet.pl',
  'politikerclub.de',
  'pooch.com',
  'pookmail.com',
  'popesodomy.com',
  'postacı.com',
  'powered.name',
  'privacy.net',
  'proxymail.eu',
  'punkass.com',
  'putthisinyourspamdatabase.com',
  'qq.com',
  'quickinbox.com',
  'rcpt.at',
  'recode.me',
  'recursor.net',
  'regbypass.comsafe-mail.net',
  'rmqkr.net',
  'royal.net',
  'rppkn.com',
  's0ny.net',
  'safe-mail.net',
  'safetypost.de',
  'sandelf.de',
  'saynotospams.com',
  'sharedmailbox.org',
  'shiftmail.com',
  'shortmail.net',
  'sikux.com',
  'sinnlos-mail.de',
  'skeefmail.com',
  'slapsfromlastnight.com',
  'slaskpost.se',
  'slavapkim.com',
  'slippery.email',
  'slopsbox.com',
  'slowfoodfoothills.org',
  'smellfear.com',
  'smrtr.io',
  'snakemail.com',
  'sneakemail.com',
  'sofimail.com',
  'sogetthis.com',
  'soodomail.com',
  'soodonims.com',
  'spam4.me',
  'spamavert.com',
  'spambob.com', 'spambob.net', 'spambob.org',
  'spambog.com', 'spambog.de', 'spambog.ru',
  'spambox.us',
  'spamcero.com',
  'spamcon.org',
  'spamcorptastic.com',
  'spamcowboy.com', 'spamcowboy.net', 'spamcowboy.org',
  'spamday.com',
  'spamex.com',
  'spamfree.eu',
  'spamfree24.de',
  'spamgrap.com',
  'spamhereplease.com',
  'spamhole.com',
  'spamify.com',
  'spaminator.de',
  'spamkill.info',
  'spamlot.net',
  'spammotel.com',
  'spamorgy.com',
  'spamotron.com',
  'spampoison.com',
  'spamprint.com',
  'spamserver.net',
  'spamslicer.com',
  'spamstack.net',
  'spamthis.co.uk',
  'spamthisplease.com',
  'spamtroll.net',
  'spamwc.de',
  'spoofmail.de',
  'stinkefinger.net',
  'stuffmail.de',
  'super-auswahl.de',
  'supergreatmail.com',
  'supermailer.jp',
  'suremail.info',
  'svk.jp',
  'sweetxxx.de',
  'tafmail.com',
  'tagyourself.com',
  'talkinator.com',
  'techemail.com',
  'tempalias.com',
  'tempe-mail.com',
  'tempemail.biz',
  'tempemail.com',
  'tempemail.net',
  'tempinbox.co.uk',
  'tempinbox.com',
  'tempmail.eu',
  'tempmail.it',
  'tempmail2.com',
  'tempomail.fr',
  'temporarioemail.com.br',
  'temporaryemail.net',
  'temporaryemail.us',
  'temporaryforwarding.com',
  'temporaryinbox.com',
  'temporarymailaddress.com',
  'thanksnospam.info',
  'thc.st',
  'thelimestones.com',
  'thisisnotmyrealemail.com',
  'thismail.net',
  'throwam.com',
  'throwjunk.com',
  'tilien.com',
  'tittbit.in',
  'tizi.com',
  'tmailinator.com',
  'toiea.com',
  'tokenmail.de',
  'top101.de',
  'topranklist.de',
  'torchmail.com',
  'tradermail.info',
  'trash-mail.at',
  'trash-mail.com',
  'trash-mail.de',
  'trash-mail.ga',
  'trash-mail.io',
  'trash-mail.net',
  'trash-mail.tk',
  'trash2009.com',
  'trashdevil.com', 'trashdevil.de',
  'trashemail.de',
  'trashimail.de',
  'trbvm.com',
  'trillianpro.com',
  'turual.com',
  'twinmail.de',
  'twoweirdtricks.com',
  'tyldd.com',
  'ubm.md',
  'uggsrock.com',
  'umail.net',
  'unlimit.com',
  'unmail.ru',
  'uroid.com',
  'us.af',
  'valemail.net',
  'venompen.com',
  'veryrealemail.com',
  'vfemail.net',
  'viditag.com',
  'viewcastmedia.com',
  'viewcastmedia.net',
  'viewcastmedia.org',
  'vomoto.com',
  'vpn.st',
  'vsimcard.com',
  'vubby.com',
  'walala.org',
  'walkmail.net',
  'wasteland.rfc822.org',
  'watch-harry-potter.com',
  'webemail.me',
  'weg-werf-email.de',
  'wegwerf-emails.de',
  'wegwerfadresse.de',
  'wegwerfemail.com', 'wegwerfemail.de', 'wegwerfemail.net', 'wegwerfemail.org',
  'wegwerfmail.de', 'wegwerfmail.info', 'wegwerfmail.net', 'wegwerfmail.org',
  'wegwerfmailaddresse.de',
  'wetrainbayarea.com', 'wetrainbayarea.org',
  'whyspam.me',
  'willhackforfood.biz',
  'willselfdestruct.com',
  'wmail.cf',
  'wolfsmail.tk',
  'wuzupmail.net',
  'www.e4ward.com',
  'www.gishpuppy.com',
  'www.mailinator.com',
  'xagloo.com',
  'xemaps.com',
  'xents.com',
  'xmaily.com',
  'xoxy.net',
  'xyzfree.net',
  'yapped.net',
  'yeah.net',
  'yep.it',
  'yogamaven.com',
  'yomail.info',
  'yoyo.com',
  'ypmail.webarnak.fr.eu.org',
  'yuurok.com',
  'z1p.biz',
  'za.com',
  'zehnminutenmail.de',
  'zetmail.com',
  'zippymail.info',
  'zoemail.net', 'zoemail.org',
  'zomg.info',
  // ── Additional common ones ───────────────────────────────────
  'inoutmail.eu', 'inoutmail.de', 'inoutmail.info', 'inoutmail.net',
  'mailboxy.fun',
  'filtr.one',
  'spamwc.net',
  'hidzz.com',
  'meinspamschutz.de',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monmail.fr.nf',
]);

/**
 * Returns true if the email domain is a known disposable/temp email provider.
 * Apple Private Relay emails (privaterelay.appleid.com) are always allowed.
 */
export function isDisposableEmail(email: string): boolean {
  if (!email || !email.includes('@')) return false;
  const domain = email.split('@')[1]?.toLowerCase().trim();
  if (!domain) return false;
  // Apple Private Relay is legitimate — never block it
  if (domain === 'privaterelay.appleid.com') return false;
  return TEMP_EMAIL_DOMAINS.has(domain);
}
