/**
 * translateHelper.ts
 *
 * Custom localized mapping helper for database values and dynamic AI strings
 * (e.g. week themes, day focus points, nutrient labels, meal types)
 * that aren't easily stored inside static JSON localization tables.
 */

const DICT: Record<string, Record<string, string>> = {
  pt: {
    'Full Body': 'Corpo Inteiro',
    'Full body': 'Corpo inteiro',
    'Full Body Strength': 'Força de Corpo Inteiro',
    'Full Body Power': 'Potência de Corpo Inteiro',
    'Zone 2 Cardio': 'Cardio Zona 2',
    'Recovery': 'Recuperação',
    'Foundation': 'Fundação',
    'Strength': 'Força',
    'Conditioning': 'Condicionamento',
    'Performance': 'Desempenho',
    'Phase': 'Fase',
    'Upper Body Push': 'Empurrar Tronco Superior',
    'Lower Body': 'Tronco Inferior',
    'Upper Body Pull': 'Puxar Tronco Superior',
    'Core Stability': 'Estabilidade do Core',
    'HIIT Circuit': 'Circuito HIIT',
    'Strength Endurance': 'Resistência de Força',
    'Zone 2 + Mobility': 'Zona 2 + Mobilidade',
    'Lower Body Endurance': 'Resistência do Tronco Inferior',
    'Heavy Compound Day': 'Dia de Compostos Pesados',
    'Power & Agility': 'Potência e Agilidade',
    'Mobility & Deload': 'Mobilidade e Descarga',
    'Final Test Day': 'Dia de Teste Final',
    'Total Fat': 'Gordura Total',
    'Saturated Fat': 'Gordura Saturada',
    'Trans Fat': 'Gordura Trans',
    'Monounsaturated Fat': 'Gordura Monoinsaturada',
    'Polyunsaturated Fat': 'Gordura Poliinsaturada',
    'Total Carbohydrates': 'Carboidratos Totais',
    'Total Carbohydrate': 'Carboidratos Totais',
    'Dietary Fiber': 'Fibra Alimentar',
    'Sugars': 'Açúcares',
    'Total Sugars': 'Açúcares Totais',
    'Added Sugar': 'Açúcar Adicionado',
    'Total Protein': 'Proteína Total',
    'Sodium': 'Sódio',
    'Potassium': 'Potássio',
    'Iron': 'Ferro',
    'Calcium': 'Cálcio',
    'Magnesium': 'Magnésio',
    'Zinc': 'Zinco',
    'Vitamin A': 'Vitamina A',
    'Vitamin C': 'Vitamina C',
    'Calories': 'Calorias',
    'Protein': 'Proteína',
    'Carbs': 'Carboidratos',
    'Fat': 'Gordura',
    'Breakfast': 'Pequeno-almoço',
    'Lunch': 'Almoço',
    'Dinner': 'Jantar',
    'Snack': 'Lanche',
    'Walk / cycle': 'Caminhar / pedalar',
    'Mobility finisher': 'Finalizador de mobilidade',
    'Walk / cycle, Mobility finisher': 'Caminhada/pedalada, finalizador de mobilidade',
    'Stretching, Easy walk': 'Alongamento, caminhada leve',
    'Stretching': 'Alongamento',
    'Easy walk': 'Caminhada leve',
    'Abs, Obliques, Lower Back': 'Abs, oblíquos, lombar',
    'Cardio': 'Cardio',
    'Mobility': 'Mobilidade',
    'Zone 2 cardio': 'Cardio zona 2',
    'Cardio, Flexibility': 'Cardio, flexibilidade',
    'Abs': 'Abdominais',
    'Obliques': 'Oblíquos',
    'Lower Back': 'Lombar',
    'No foods logged today': 'Nenhum Alimento Registado Hoje',
    'Log meals to see your detailed nutrition insights here.': 'Registe refeições para ver os seus insights de nutrição detalhados aqui.',
    'Fat Breakdown': 'Divisão de Gordura',
    'Cardiovascular profiling & hormone synthesis': 'Perfil cardiovascular e síntese hormonal',
    'Carbs & Blood Sugar': 'Carboidratos e Açúcar no Sangue',
    'Sugar control & fasting intelligence': 'Controlo de açúcar e inteligência de jejum',
    'Detailed Nutrition': 'Nutrição Detalhada',
    'foods': 'alimentos',
    'Rotates in': 'Roda em',
    'days': 'dias',
    'day': 'dia',
    'Rotating soon…': 'Rodando em breve…',
    'Balanced': 'Equilibrado',
    'High Protein': 'Alta Proteína',
    'Low Carb': 'Baixo Carboidrato',
    'Plant Based': 'À Base de Plantas',
    'Flexible': 'Flexível',
    'Scan Food': 'Escanear Alimento',
    'Nutrition Label': 'Rótulo Nutricional',
    'Continue Your Journey': 'Continue a Sua Jornada',
    'Free users get a full 28-day plan. When you finish, upgrade to Pro to continue your transformation with an AI-generated plan.': 'Utilizadores gratuitos recebem um plano de 28 dias. Ao terminar, atualize para Pro para continuar.',
    'Upgrade to Pro': 'Atualizar para Pro'
  },
  nl: {
    'Full Body': 'Volledige Lichaam',
    'Full body': 'Volledige lichaam',
    'Full Body Strength': 'Volledige Lichaamskracht',
    'Full Body Power': 'Volledige Lichaamskracht',
    'Zone 2 Cardio': 'Zone 2 Cardio',
    'Recovery': 'Herstel',
    'Foundation': 'Basis',
    'Strength': 'Kracht',
    'Conditioning': 'Conditie',
    'Performance': 'Prestatie',
    'Phase': 'Fase',
    'Upper Body Push': 'Bovenlichaam Push',
    'Lower Body': 'Onderlichaam',
    'Upper Body Pull': 'Bovenlichaam Pull',
    'Core Stability': 'Rompstabiliteit',
    'HIIT Circuit': 'HIIT-circuit',
    'Strength Endurance': 'Krachtuithoudingsvermogen',
    'Zone 2 + Mobility': 'Zone 2 + Mobiliteit',
    'Lower Body Endurance': 'Onderlichaam Uithoudingsvermogen',
    'Heavy Compound Day': 'Zware Samengestelde Dag',
    'Power & Agility': 'Kracht & Wendbaarheid',
    'Mobility & Deload': 'Mobiliteit & Deload',
    'Final Test Day': 'Laatste Testdag',
    'Total Fat': 'Vet Totaal',
    'Saturated Fat': 'Verzadigd Vet',
    'Trans Fat': 'Transvet',
    'Monounsaturated Fat': 'Enkelvoudig Onverzadigd Vet',
    'Polyunsaturated Fat': 'Meervoudig Onverzadigd Vet',
    'Total Carbohydrates': 'Koolhydraten Totaal',
    'Total Carbohydrate': 'Koolhydraten Totaal',
    'Dietary Fiber': 'Voedingsvezels',
    'Sugars': 'Suikers',
    'Total Sugars': 'Suikers Totaal',
    'Added Sugar': 'Toegevoegde Suiker',
    'Total Protein': 'Eiwit Totaal',
    'Sodium': 'Natrium',
    'Potassium': 'Kalium',
    'Iron': 'IJzer',
    'Calcium': 'Calcium',
    'Magnesium': 'Magnesium',
    'Zinc': 'Zink',
    'Vitamin A': 'Vitamine A',
    'Vitamin C': 'Vitamine C',
    'Calories': 'Calorieën',
    'Protein': 'Eiwitten',
    'Carbs': 'Koolhydraten',
    'Fat': 'Vet',
    'Breakfast': 'Ontbijt',
    'Lunch': 'Lunch',
    'Dinner': 'Diner',
    'Snack': 'Snack',
    'Walk / cycle': 'Wandelen / fietsen',
    'Mobility finisher': 'Mobiliteit finisher',
    'Walk / cycle, Mobility finisher': 'Wandelen / fietsen, mobiliteit finisher',
    'Stretching, Easy walk': 'Strekken, rustige wandeling',
    'Stretching': 'Strekken',
    'Easy walk': 'Rustige wandeling',
    'Abs, Obliques, Lower Back': 'Buikspieren, schuine buikspieren, onderrug',
    'Cardio': 'Cardio',
    'Mobility': 'Mobiliteit',
    'Zone 2 cardio': 'Zone 2 cardio',
    'Cardio, Flexibility': 'Cardio, flexibiliteit',
    'Abs': 'Buikspieren',
    'Obliques': 'Schuine buikspieren',
    'Lower Back': 'Onderrug',
    'No foods logged today': 'Geen maaltijden geregistreerd vandaag',
    'Log meals to see your detailed nutrition insights here.': 'Registreer maaltijden om hier uw gedetailleerde voedingsinzichten te zien.',
    'Fat Breakdown': 'Vetverdeling',
    'Cardiovascular profiling & hormone synthesis': 'Cardiovasculaire profilering & hormonsyntese',
    'Carbs & Blood Sugar': 'Koolhydraten & Bloedsuikerspiegel',
    'Sugar control & fasting intelligence': 'Suikercontrole & vasten intelligentie',
    'Detailed Nutrition': 'Gedetailleerde Voeding',
    'foods': 'voedingsmiddelen',
    'Rotates in': 'Roteert over',
    'days': 'dagen',
    'day': 'dag',
    'Rotating soon…': 'Roteert binnenkort…',
    'Balanced': 'Gebalanceerd',
    'High Protein': 'Eiwitrijk',
    'Low Carb': 'Koolhydraatarm',
    'Plant Based': 'Plantaardig',
    'Flexible': 'Flexibel',
    'Scan Food': 'Eten Scannen',
    'Nutrition Label': 'Voedingswaardeetiket',
    'Continue Your Journey': 'Vervolg Je Reis',
    'Free users get a full 28-day plan. When you finish, upgrade to Pro to continue your transformation with an AI-generated plan.': 'Gratis gebruikers krijgen een plan van 28 dagen. Upgrade naar Pro om door te gaan.',
    'Upgrade to Pro': 'Upgraden naar Pro'
  },
  da: {
    'Full Body': 'Hele Kroppen',
    'Full body': 'Hele kroppen',
    'Full Body Strength': 'Styrke for Hele Kroppen',
    'Full Body Power': 'Styrke for Hele Kroppen',
    'Zone 2 Cardio': 'Zone 2 Cardio',
    'Recovery': 'Restitution',
    'Foundation': 'Fundament',
    'Strength': 'Styrke',
    'Conditioning': 'Konditionering',
    'Performance': 'Ydeevne',
    'Phase': 'Fase',
    'Upper Body Push': 'Overkrop Pres',
    'Lower Body': 'Underkrop',
    'Upper Body Pull': 'Overkrop Træk',
    'Core Stability': 'Core Stabilitet',
    'HIIT Circuit': 'HIIT Kredsløb',
    'Strength Endurance': 'Styrkeudholdenhed',
    'Zone 2 + Mobility': 'Zone 2 + Mobilitet',
    'Lower Body Endurance': 'Underkrop Udholdenhed',
    'Heavy Compound Day': 'Tung Flerledsdag',
    'Power & Agility': 'Styrke & Smidighed',
    'Mobility & Deload': 'Mobilitet & Deload',
    'Final Test Day': 'Sidste Testdag',
    'Total Fat': 'Fedt I alt',
    'Saturated Fat': 'Mættet Fedt',
    'Trans Fat': 'Transfedt',
    'Monounsaturated Fat': 'Monoumættet Fedt',
    'Polyunsaturated Fat': 'Polyumættet Fedt',
    'Total Carbohydrates': 'Kulhydrat I alt',
    'Total Carbohydrate': 'Kulhydrat I alt',
    'Dietary Fiber': 'Kostfibre',
    'Sugars': 'Sukkerarter',
    'Total Sugars': 'Sukker I alt',
    'Added Sugar': 'Tilsat Sukker',
    'Total Protein': 'Protein I alt',
    'Sodium': 'Natrium',
    'Potassium': 'Kalium',
    'Iron': 'Jern',
    'Calcium': 'Calcium',
    'Magnesium': 'Magnesium',
    'Zinc': 'Zink',
    'Vitamin A': 'Vitamin A',
    'Vitamin C': 'Vitamin C',
    'Calories': 'Kalorier',
    'Protein': 'Protein',
    'Carbs': 'Kulhydrater',
    'Fat': 'Fedt',
    'Breakfast': 'Morgenmad',
    'Lunch': 'Frokost',
    'Dinner': 'Aftensmad',
    'Snack': 'Mellemmåltid',
    'Walk / cycle': 'Gå / cykle',
    'Mobility finisher': 'Mobilitetsafslutning',
    'Walk / cycle, Mobility finisher': 'Gå/cykle, mobilitetsafslutning',
    'Stretching, Easy walk': 'Stræk, let gang',
    'Stretching': 'Stræk',
    'Easy walk': 'Let gang',
    'Abs, Obliques, Lower Back': 'Abs, obliquer, lænd',
    'Cardio': 'Kredsløb',
    'Mobility': 'Mobilitet',
    'Zone 2 cardio': 'Zone 2 cardio',
    'Cardio, Flexibility': 'Kredsløb, fleksibilitet',
    'Abs': 'Abs',
    'Obliques': 'Obliquer',
    'Lower Back': 'Lænd',
    'No foods logged today': 'Ingen mad registreret i dag',
    'Log meals to see your detailed nutrition insights here.': 'Registrer måltider for at se dine detaljerede ernæringsindsigter her.',
    'Fat Breakdown': 'Fedtfordeling',
    'Cardiovascular profiling & hormone synthesis': 'Kredsløbsprofilering & hormonsyntese',
    'Carbs & Blood Sugar': 'Kulhydrater & Blodsukker',
    'Sugar control & fasting intelligence': 'Sukkerkontrol & fastetolerance',
    'Detailed Nutrition': 'Detaljeret Ernæring',
    'foods': 'madvarer',
    'Rotates in': 'Roterer om',
    'days': 'dage',
    'day': 'dag',
    'Rotating soon…': 'Roterer snart…',
    'Balanced': 'Balanceret',
    'High Protein': 'Højt Protein',
    'Low Carb': 'Få Kulhydrater',
    'Plant Based': 'Plantebaseret',
    'Flexible': 'Fleksibel',
    'Scan Food': 'Scan Mad',
    'Nutrition Label': 'Næringsdeklaration',
    'Continue Your Journey': 'Fortsæt Din Rejse',
    'Free users get a full 28-day plan. When you finish, upgrade to Pro to continue your transformation with an AI-generated plan.': 'Gratis brugere får en 28-dages plan. Opgrader til Pro for at fortsætte med en AI-plan.',
    'Upgrade to Pro': 'Opgrader til Pro'
  },
  no: {
    'Full Body': 'Hele Kroppen',
    'Full body': 'Hele kroppen',
    'Full Body Strength': 'Styrke for Hele Kroppen',
    'Full Body Power': 'Styrke for Hele Kroppen',
    'Zone 2 Cardio': 'Sone 2 Kardio',
    'Recovery': 'Restitusjon',
    'Foundation': 'Fundament',
    'Strength': 'Styrke',
    'Conditioning': 'Kondisjonering',
    'Performance': 'Ytelse',
    'Phase': 'Fase',
    'Upper Body Push': 'Overkropp Press',
    'Lower Body': 'Underkropp',
    'Upper Body Pull': 'Overkropp Trekk',
    'Core Stability': 'Kjernestabilitet',
    'HIIT Circuit': 'HIIT-Krets',
    'Strength Endurance': 'Styrkeutholdenhet',
    'Zone 2 + Mobility': 'Sone 2 + Mobilitet',
    'Lower Body Endurance': 'Underkropp Utholdenhet',
    'Heavy Compound Day': 'Tung Flerleddsdag',
    'Power & Agility': 'Styrke & Smidighet',
    'Mobility & Deload': 'Mobilitet & Deload',
    'Final Test Day': 'Siste Testdag',
    'Total Fat': 'Fett totalt',
    'Saturated Fat': 'Mettet Fett',
    'Trans Fat': 'Transfett',
    'Monounsaturated Fat': 'Monoumettet Fett',
    'Polyunsaturated Fat': 'Polyumettet Fett',
    'Total Carbohydrates': 'Karbohydrater totalt',
    'Total Carbohydrate': 'Karbohydrater totalt',
    'Dietary Fiber': 'Kostfiber',
    'Sugars': 'Sukkerarter',
    'Total Sugars': 'Sukker totalt',
    'Added Sugar': 'Tilsatt Sukker',
    'Total Protein': 'Protein totalt',
    'Sodium': 'Natrium',
    'Potassium': 'Kalium',
    'Iron': 'Jern',
    'Calcium': 'Kalsium',
    'Magnesium': 'Magnesium',
    'Zinc': 'Sink',
    'Vitamin A': 'Vitamin A',
    'Vitamin C': 'Vitamin C',
    'Calories': 'Kalorier',
    'Protein': 'Protein',
    'Carbs': 'Karbohydrater',
    'Fat': 'Fett',
    'Breakfast': 'Frokost',
    'Lunch': 'Lunsj',
    'Dinner': 'Middag',
    'Snack': 'Mellommåltid',
    'Walk / cycle': 'Gå / sykle',
    'Mobility finisher': 'Mobilitetsavslutning',
    'Walk / cycle, Mobility finisher': 'Gå/sykle, mobilitetsavslutning',
    'Stretching, Easy walk': 'Tøying, lett gange',
    'Stretching': 'Tøying',
    'Easy walk': 'Lett gange',
    'Abs, Obliques, Lower Back': 'Abs, obliquer, korsrygg',
    'Cardio': 'Kardio',
    'Mobility': 'Mobilitet',
    'Zone 2 cardio': 'Sone 2 kardio',
    'Cardio, Flexibility': 'Kardio, fleksibilitet',
    'Abs': 'Abs',
    'Obliques': 'Obliquer',
    'Lower Back': 'Korsrygg',
    'No foods logged today': 'Ingen mat registrert i dag',
    'Log meals to see your detailed nutrition insights here.': 'Registrer måltider for å se detaljert ernæring her.',
    'Fat Breakdown': 'Fettnedbrytning',
    'Cardiovascular profiling & hormone synthesis': 'Kardiovaskulær profil & hormonsyntese',
    'Carbs & Blood Sugar': 'Karbohydrater & Blodsukker',
    'Sugar control & fasting intelligence': 'Sukkerkontroll & fasteintelligens',
    'Detailed Nutrition': 'Detaljert Ernæring',
    'foods': 'matvarer',
    'Rotates in': 'Roterer om',
    'days': 'dager',
    'day': 'dag',
    'Rotating soon…': 'Roterer snart…',
    'Balanced': 'Balansert',
    'High Protein': 'Høyt Protein',
    'Low Carb': 'Få Karbohydrater',
    'Plant Based': 'Plantebasert',
    'Flexible': 'Fleksibel',
    'Scan Food': 'Skann Mat',
    'Nutrition Label': 'Næringsdeklarasjon',
    'Continue Your Journey': 'Fortsett Reisen',
    'Free users get a full 28-day plan. When you finish, upgrade to Pro to continue your transformation with an AI-generated plan.': 'Gratis brukere får en 28-dagers plan. Oppgrader til Pro for å fortsette med en AI-plan.',
    'Upgrade to Pro': 'Oppgrader til Pro'
  },
  sv: {
    'Full Body': 'Helkropp',
    'Full body': 'Helkropp',
    'Full Body Strength': 'Styrka för Helkropp',
    'Full Body Power': 'Styrka för Helkropp',
    'Zone 2 Cardio': 'Zon 2 Cardio',
    'Recovery': 'Återhämtning',
    'Foundation': 'Grundläggande',
    'Strength': 'Styrka',
    'Conditioning': 'Kondition',
    'Performance': 'Prestation',
    'Phase': 'Fas',
    'Upper Body Push': 'Överkropp Press',
    'Lower Body': 'Underkropp',
    'Upper Body Pull': 'Överkropp Drag',
    'Core Stability': 'Bålstabilitet',
    'HIIT Circuit': 'HIIT-Krets',
    'Strength Endurance': 'Styrkeuthållighet',
    'Zone 2 + Mobility': 'Zon 2 + Mobilitet',
    'Lower Body Endurance': 'Underkropp Uthållighet',
    'Heavy Compound Day': 'Tung Flerledsdag',
    'Power & Agility': 'Styrka & Rörlighet',
    'Mobility & Deload': 'Rörlighet & Deload',
    'Final Test Day': 'Sista Testdagen',
    'Total Fat': 'Fett totalt',
    'Saturated Fat': 'Mättat Fett',
    'Trans Fat': 'Transfett',
    'Monounsaturated Fat': 'Enkelomättat Fett',
    'Polyunsaturated Fat': 'Fleromättat Fett',
    'Total Carbohydrates': 'Kolhydrater totalt',
    'Total Carbohydrate': 'Kolhydrater totalt',
    'Dietary Fiber': 'Kostfiber',
    'Sugars': 'Sockerarter',
    'Total Sugars': 'Socker totalt',
    'Added Sugar': 'Tillsatt Socker',
    'Total Protein': 'Protein totalt',
    'Sodium': 'Natrium',
    'Potassium': 'Kalium',
    'Iron': 'Järn',
    'Calcium': 'Kalcium',
    'Magnesium': 'Magnesium',
    'Zinc': 'Zink',
    'Vitamin A': 'Vitamin A',
    'Vitamin C': 'Vitamin C',
    'Calories': 'Kalorier',
    'Protein': 'Protein',
    'Carbs': 'Kolhydrater',
    'Fat': 'Fett',
    'Breakfast': 'Frukost',
    'Lunch': 'Lunch',
    'Dinner': 'Middag',
    'Snack': 'Mellanmål',
    'Walk / cycle': 'Gå / cykla',
    'Mobility finisher': 'Mobilitetsavslutning',
    'Walk / cycle, Mobility finisher': 'Gå/cykla, mobilitetsavslutning',
    'Stretching, Easy walk': 'Stretching, lätt promenad',
    'Stretching': 'Stretching',
    'Easy walk': 'Lätt promenad',
    'Abs, Obliques, Lower Back': 'Abs, obliquer, ländrygg',
    'Cardio': 'Kondition',
    'Mobility': 'Mobilitet',
    'Zone 2 cardio': 'Zon 2 cardio',
    'Cardio, Flexibility': 'Kondition, flexibilitet',
    'Abs': 'Abs',
    'Obliques': 'Obliquer',
    'Lower Back': 'Ländrygg',
    'No foods logged today': 'Ingen mat registrerad idag',
    'Log meals to see your detailed nutrition insights here.': 'Registrera måltider för att se dina detaljerade ernäringsinsikter här.',
    'Fat Breakdown': 'Fettfördelning',
    'Cardiovascular profiling & hormone synthesis': 'Hjärt-kärlprofil & hormonsyntes',
    'Carbs & Blood Sugar': 'Kolhydrater & Blodsocker',
    'Sugar control & fasting intelligence': 'Sockerkontroll & fasteintelligens',
    'Detailed Nutrition': 'Detaljerad Näring',
    'foods': 'livsmedel',
    'Rotates in': 'Roterar om',
    'days': 'dagar',
    'day': 'dag',
    'Rotating soon…': 'Roterar snart…',
    'Balanced': 'Balanserad',
    'High Protein': 'Högt Protein',
    'Low Carb': 'Lågkolhydrat',
    'Plant Based': 'Växtbaserad',
    'Flexible': 'Flexibel',
    'Scan Food': 'Skanna Mat',
    'Nutrition Label': 'Näringsdeklaration',
    'Continue Your Journey': 'Fortsätt Din Resa',
    'Free users get a full 28-day plan. When you finish, upgrade to Pro to continue your transformation with an AI-generated plan.': 'Gratis användare får en 28-dagars plan. Uppgradera till Pro för att fortsätta med en AI-plan.',
    'Upgrade to Pro': 'Uppgradera till Pro'
  },
  fr: {
    'Full Body': 'Corps Entier',
    'Full body': 'Corps entier',
    'Full Body Strength': 'Force du Corps Entier',
    'Full Body Power': 'Force du Corps Entier',
    'Zone 2 Cardio': 'Cardio Zone 2',
    'Recovery': 'Récupération',
    'Foundation': 'Fondation',
    'Strength': 'Force',
    'Conditioning': 'Conditionnement',
    'Performance': 'Performance',
    'Phase': 'Phase',
    'Upper Body Push': 'Haut du Corps Poussée',
    'Lower Body': 'Bas du Corps',
    'Upper Body Pull': 'Haut du Corps Tirage',
    'Core Stability': 'Stabilité du Core',
    'HIIT Circuit': 'Circuit HIIT',
    'Strength Endurance': 'Force Endurance',
    'Zone 2 + Mobility': 'Zone 2 + Mobilité',
    'Lower Body Endurance': 'Endurance Bas du Corps',
    'Heavy Compound Day': 'Jour de Composés Lourds',
    'Power & Agility': 'Puissance & Agilité',
    'Mobility & Deload': 'Mobilité & Décharge',
    'Final Test Day': 'Jour de Test Final',
    'Total Fat': 'Lipides Totaux',
    'Saturated Fat': 'Graisses Saturées',
    'Trans Fat': 'Graisses Trans',
    'Monounsaturated Fat': 'Graisses Mono-insaturées',
    'Polyunsaturated Fat': 'Graisses Poly-insaturées',
    'Total Carbohydrates': 'Glucides Totaux',
    'Total Carbohydrate': 'Glucides Totaux',
    'Dietary Fiber': 'Fibres Alimentaires',
    'Sugars': 'Sucres',
    'Total Sugars': 'Sucres Totaux',
    'Added Sugar': 'Sucre Ajouté',
    'Total Protein': 'Protéines Totales',
    'Sodium': 'Sodium',
    'Potassium': 'Potassium',
    'Iron': 'Fer',
    'Calcium': 'Calcium',
    'Magnesium': 'Magnésium',
    'Zinc': 'Zinc',
    'Vitamin A': 'Vitamine A',
    'Vitamin C': 'Vitamine C',
    'Calories': 'Calories',
    'Protein': 'Protéines',
    'Carbs': 'Glucides',
    'Fat': 'Lipides',
    'Breakfast': 'Petit Déjeuner',
    'Lunch': 'Déjeuner',
    'Dinner': 'Dîner',
    'Snack': 'Collation',
    'Walk / cycle': 'Marcher / faire du vélo',
    'Mobility finisher': 'Finisseur de mobilité',
    'Walk / cycle, Mobility finisher': 'Marche/vélo, finisseur de mobilité',
    'Stretching, Easy walk': 'Étirements, marche facile',
    'Stretching': 'Étirements',
    'Easy walk': 'Marche facile',
    'Abs, Obliques, Lower Back': 'Abs, obliques, bas du dos',
    'Cardio': 'Cardio',
    'Mobility': 'Mobilité',
    'Zone 2 cardio': 'Cardio zone 2',
    'Cardio, Flexibility': 'Cardio, flexibilité',
    'Abs': 'Abs',
    'Obliques': 'Obliques',
    'Lower Back': 'Bas du dos',
    'No foods logged today': 'Aucun aliment enregistré aujourd\'hui',
    'Log meals to see your detailed nutrition insights here.': 'Enregistrez des repas pour voir vos analyses nutritionnelles ici.',
    'Fat Breakdown': 'Répartition des Lipides',
    'Cardiovascular profiling & hormone synthesis': 'Profil cardiovasculaire & synthèse hormonale',
    'Carbs & Blood Sugar': 'Glucides & Glycémie',
    'Sugar control & fasting intelligence': 'Contrôle du sucre & intelligence du jeûne',
    'Detailed Nutrition': 'Nutrition Détaillée',
    'foods': 'aliments',
    'Rotates in': 'Tourne dans',
    'days': 'jours',
    'day': 'jour',
    'Rotating soon…': 'Tourne bientôt…',
    'Balanced': 'Équilibré',
    'High Protein': 'Riche en Protéines',
    'Low Carb': 'Faible en Glucides',
    'Plant Based': 'À Base de Plantes',
    'Flexible': 'Flexible',
    'Scan Food': 'Scanner l\'aliment',
    'Nutrition Label': 'Étiquette nutritionnelle',
    'Continue Your Journey': 'Continuez Votre Parcours',
    'Free users get a full 28-day plan. When you finish, upgrade to Pro to continue your transformation with an AI-generated plan.': 'Les utilisateurs gratuits ont un plan de 28 jours. Mettez à niveau vers Pro pour continuer avec un plan IA.',
    'Upgrade to Pro': 'Passer à la version Pro'
  },
  de: {
    'Full Body': 'Ganzkörper',
    'Full body': 'Ganzkörper',
    'Full Body Strength': 'Ganzkörperkraft',
    'Full Body Power': 'Ganzkörperkraft',
    'Zone 2 Cardio': 'Zone 2 Cardio',
    'Recovery': 'Erholung',
    'Foundation': 'Fundament',
    'Strength': 'Kraft',
    'Conditioning': 'Kondition',
    'Performance': 'Leistung',
    'Phase': 'Phase',
    'Upper Body Push': 'Oberkörper Drücken',
    'Lower Body': 'Unterkörper',
    'Upper Body Pull': 'Oberkörper Ziehen',
    'Core Stability': 'Rumpfstabilität',
    'HIIT Circuit': 'HIIT-Zirkel',
    'Strength Endurance': 'Kraftausdauer',
    'Zone 2 + Mobility': 'Zone 2 + Mobilität',
    'Lower Body Endurance': 'Unterkörperausdauer',
    'Heavy Compound Day': 'Schwerer Grundübungstag',
    'Power & Agility': 'Kraft & Agilität',
    'Mobility & Deload': 'Mobilität & Entlastung',
    'Final Test Day': 'Finaler Testtag',
    'Total Fat': 'Gesamtfett',
    'Saturated Fat': 'Gesättigte Fettsäuren',
    'Trans Fat': 'Trans-Fettsäuren',
    'Monounsaturated Fat': 'Einfach ungesättigte Fettsäuren',
    'Polyunsaturated Fat': 'Mehrfach ungesättigte Fettsäuren',
    'Total Carbohydrates': 'Kohlenhydrate gesamt',
    'Total Carbohydrate': 'Kohlenhydrate gesamt',
    'Dietary Fiber': 'Ballaststoffe',
    'Sugars': 'Zucker',
    'Total Sugars': 'Zucker gesamt',
    'Added Sugar': 'Zugesetzter Zucker',
    'Total Protein': 'Gesamtprotein',
    'Sodium': 'Natrium',
    'Potassium': 'Kalium',
    'Iron': 'Eisen',
    'Calcium': 'Kalzium',
    'Magnesium': 'Magnesium',
    'Zinc': 'Zink',
    'Vitamin A': 'Vitamin A',
    'Vitamin C': 'Vitamin C',
    'Calories': 'Kalorien',
    'Protein': 'Protein',
    'Carbs': 'Kohlenhydrate',
    'Fat': 'Fett',
    'Breakfast': 'Frühstück',
    'Lunch': 'Mittagessen',
    'Dinner': 'Abendessen',
    'Snack': 'Snack',
    'Walk / cycle': 'Gehen / Radfahren',
    'Mobility finisher': 'Mobilitäts-Finisher',
    'Walk / cycle, Mobility finisher': 'Gehen/Radfahren, Mobilitäts-Finisher',
    'Stretching, Easy walk': 'Dehnen, leichter Spaziergang',
    'Stretching': 'Dehnen',
    'Easy walk': 'Leichter Spaziergang',
    'Abs, Obliques, Lower Back': 'Abs, Bauchmuskeln, unterer Rücken',
    'Cardio': 'Kardio',
    'Mobility': 'Mobilität',
    'Zone 2 cardio': 'Zone 2 Kardio',
    'Cardio, Flexibility': 'Kardio, Flexibilität',
    'Abs': 'Abs',
    'Obliques': 'Seitliche Bauchmuskeln',
    'Lower Back': 'Unterer Rücken',
    'No foods logged today': 'Heute keine Mahlzeiten eingetragen',
    'Log meals to see your detailed nutrition insights here.': 'Trage Mahlzeiten ein, um hier Details zu sehen.',
    'Fat Breakdown': 'Fettaufteilung',
    'Cardiovascular profiling & hormone synthesis': 'Kardiovaskuläres Profil & Hormonsynthese',
    'Carbs & Blood Sugar': 'Kohlenhydrate & Blutzucker',
    'Sugar control & fasting intelligence': 'Zuckerkontrolle & Fastenintelligenz',
    'Detailed Nutrition': 'Detaillierte Ernährung',
    'foods': 'Lebensmittel',
    'Rotates in': 'Rotiert in',
    'days': 'Tagen',
    'day': 'Tag',
    'Rotating soon…': 'Rotiert bald…',
    'Balanced': 'Ausgewogen',
    'High Protein': 'Proteinreich',
    'Low Carb': 'Low-Carb',
    'Plant Based': 'Pflanzlich',
    'Flexible': 'Flexibel',
    'Scan Food': 'Essen Scannen',
    'Nutrition Label': 'Nährwerttabelle',
    'Continue Your Journey': 'Setze Deine Reise Fort',
    'Free users get a full 28-day plan. When you finish, upgrade to Pro to continue your transformation with an AI-generated plan.': 'Kostenlose Nutzer erhalten einen 28-Tage-Plan. Aktualisiere auf Pro, um mit einem KI-Plan fortzufahren.',
    'Upgrade to Pro': 'Auf Pro upgraden'
  },
  es: {
    'Full Body': 'Cuerpo Completo',
    'Full body': 'Cuerpo completo',
    'Full Body Strength': 'Fuerza de Cuerpo Completo',
    'Full Body Power': 'Fuerza de Cuerpo Completo',
    'Zone 2 Cardio': 'Cardio Zona 2',
    'Recovery': 'Recuperación',
    'Foundation': 'Fundación',
    'Strength': 'Fuerza',
    'Conditioning': 'Acondicionamiento',
    'Performance': 'Rendimiento',
    'Phase': 'Fase',
    'Upper Body Push': 'Empuje de Tronco Superior',
    'Lower Body': 'Tronco Inferior',
    'Upper Body Pull': 'Tirón de Tronco Superior',
    'Core Stability': 'Estabilidad del Core',
    'HIIT Circuit': 'Circuito HIIT',
    'Strength Endurance': 'Resistencia de Fuerza',
    'Zone 2 + Mobility': 'Zona 2 + Movilidad',
    'Lower Body Endurance': 'Resistencia de Tronco Inferior',
    'Heavy Compound Day': 'Día de Compuestos Pesados',
    'Power & Agility': 'Potencia y Agilidad',
    'Mobility & Deload': 'Movilidad y Descarga',
    'Final Test Day': 'Día de Prueba Final',
    'Total Fat': 'Grasas Totales',
    'Saturated Fat': 'Grasas Saturadas',
    'Trans Fat': 'Grasas Trans',
    'Monounsaturated Fat': 'Grasas Monoinsaturadas',
    'Polyunsaturated Fat': 'Grasas Poliinsaturadas',
    'Total Carbohydrates': 'Carbohidratos Totales',
    'Total Carbohydrate': 'Carbohidratos Totales',
    'Dietary Fiber': 'Fibra Alimentaria',
    'Sugars': 'Azúcares',
    'Total Sugars': 'Azúcares Totales',
    'Added Sugar': 'Azúcar Añadido',
    'Total Protein': 'Proteína Total',
    'Sodium': 'Sodio',
    'Potassium': 'Potasio',
    'Iron': 'Hierro',
    'Calcium': 'Calcio',
    'Magnesium': 'Magnesio',
    'Zinc': 'Zinc',
    'Vitamin A': 'Vitamina A',
    'Vitamin C': 'Vitamina C',
    'Calories': 'Calorías',
    'Protein': 'Proteína',
    'Carbs': 'Carbohidratos',
    'Fat': 'Grasa',
    'Breakfast': 'Desayuno',
    'Lunch': 'Almuerzo',
    'Dinner': 'Cena',
    'Snack': 'Merienda',
    'Walk / cycle': 'Caminar / andar en bicicleta',
    'Mobility finisher': 'Finalizador de movilidad',
    'Walk / cycle, Mobility finisher': 'Caminar/bicicleta, finalizador de movilidad',
    'Stretching, Easy walk': 'Estiramiento, caminata ligera',
    'Stretching': 'Estiramiento',
    'Easy walk': 'Caminata ligera',
    'Abs, Obliques, Lower Back': 'Abs, oblicuos, espalda baja',
    'Cardio': 'Cardio',
    'Mobility': 'Movilidad',
    'Zone 2 cardio': 'Cardio zona 2',
    'Cardio, Flexibility': 'Cardio, flexibilidad',
    'Abs': 'Abs',
    'Obliques': 'Oblicuos',
    'Lower Back': 'Espalda baja',
    'No foods logged today': 'No se registraron alimentos hoy',
    'Log meals to see your detailed nutrition insights here.': 'Registre comidas para ver detalles de nutrición aquí.',
    'Fat Breakdown': 'Desglose de Grasas',
    'Cardiovascular profiling & hormone synthesis': 'Perfil cardiovascular y síntesis de hormonas',
    'Carbs & Blood Sugar': 'Carbohidratos y Azúcar en Sangre',
    'Sugar control & fasting intelligence': 'Control de azúcar e inteligencia de ayuno',
    'Detailed Nutrition': 'Nutrición Detalle',
    'foods': 'alimentos',
    'Rotates in': 'Rota en',
    'days': 'días',
    'day': 'día',
    'Rotating soon…': 'Rotando pronto…',
    'Balanced': 'Equilibrado',
    'High Protein': 'Alto en Proteínas',
    'Low Carb': 'Bajo en Carbohidratos',
    'Plant Based': 'A Base de Plantas',
    'Flexible': 'Flexible',
    'Scan Food': 'Escanear Comida',
    'Nutrition Label': 'Etiqueta Nutricional',
    'Continue Your Journey': 'Continúa Tu Viaje',
    'Free users get a full 28-day plan. When you finish, upgrade to Pro to continue your transformation with an AI-generated plan.': 'Los usuarios gratuitos obtienen un plan de 28 días. Actualiza a Pro para continuar con un plan de IA.',
    'Upgrade to Pro': 'Actualizar a Pro'
  }
};

export function translateValue(value: string | undefined, lang: string, t: any): string {
  if (!value) return '';
  const cleanLang = (lang || 'en').split('-')[0].toLowerCase();
  
  const trimmed = value.trim();
  const lower = trimmed.toLowerCase();

  // Try custom dictionary lookup
  const dict = DICT[cleanLang];
  if (dict) {
    if (dict[trimmed]) return dict[trimmed];
    // Case insensitive match
    const matchedKey = Object.keys(dict).find(k => k.toLowerCase() === lower);
    if (matchedKey) return dict[matchedKey];
  }

  // Fallback to query translations directly if namespaces have it
  let translated = t(`workouts.labels.${trimmed}`, '');
  if (translated) return translated;
  
  translated = t(`workouts.muscles.${trimmed}`, '');
  if (translated) return translated;

  translated = t(`workouts.categories.${trimmed}`, '');
  if (translated) return translated;

  // Day X of 28 regex matching for dynamic templates
  const dayMatch = trimmed.match(/^day\s+(\d+)\s+of\s+(\d+)$/i);
  if (dayMatch) {
    const cur = dayMatch[1];
    const tot = dayMatch[2];
    
    // Localize day progress
    if (cleanLang === 'pt') return `Dia ${cur} de ${tot}`;
    if (cleanLang === 'da') return `Dag ${cur} af ${tot}`;
    if (cleanLang === 'no') return `Dag ${cur} av ${tot}`;
    if (cleanLang === 'sv') return `Dag ${cur} av ${tot}`;
    if (cleanLang === 'fr') return `Jour ${cur} sur ${tot}`;
    if (cleanLang === 'de') return `Tag ${cur} von ${tot}`;
    if (cleanLang === 'es') return `Día ${cur} de ${tot}`;
    if (cleanLang === 'nl') return `Dag ${cur} van ${tot}`;
    if (cleanLang === 'pl') return `Dzień ${cur} z ${tot}`;
    if (cleanLang === 'tr') return `${tot} Günün ${cur}. Günü`;
    if (cleanLang === 'ro') return `Ziua ${cur} din ${tot}`;
    if (cleanLang === 'bg') return `Ден ${cur} от ${tot}`;
    if (cleanLang === 'el') return `Ημέρα ${cur} από ${tot}`;
    if (cleanLang === 'lt') return `${cur} diena iš ${tot}`;
    if (cleanLang === 'lv') return `${cur}. diena no ${tot}`;
  }

  // General cleanups for common string formats from AI plans:
  // e.g. "Full Body A" -> "Full Body" + " A"
  if (lower.startsWith('full body')) {
    const suffix = trimmed.slice(9);
    const base = dict ? (dict['Full Body'] || 'Full Body') : 'Full Body';
    return base + suffix;
  }

  return value;
}
