import json
import os

LOCALES_DIR = r"C:\Users\jwfca\Desktop\BluomAppNew\locales"

# All 19 translations mapped by locale code
TRANSLATIONS = {
    "en": {
        "title": "Bluom Pro",
        "subtitle": "Unlock your full potential",
        "bestValue": "★ BEST VALUE",
        "alreadyPro": "✦ You're Pro",
        "alreadyProSub": "Full access is active. Keep optimising.",
        "continue": "Continue",
        "trialHeader": "Here's how your free trial works",
        "step1Title": "Today: Start Your Free Trial",
        "step1Sub": "Get instant access to unlimited AI meal scans, custom workouts, mental health protocols & cycle intelligence.",
        "step2Title": "Day 5: Trial Reminder ({{date}})",
        "step2Sub": "You'll receive a push notification and email reminder that your free trial is ending soon.",
        "step3Title": "Day 7: Trial Ends ({{date}})",
        "step3Sub": "You'll be billed for your selected plan. Cancel anytime before in App Store / Play Store settings.",
        "annualTitle": "Pro Annual",
        "annualSubWithPrice": "Billed annually ({{price}})",
        "perYear": "/ yr",
        "perMonth": "/ mo",
        "perWeek": "/wk",
        "monthlyTitle": "Pro Monthly",
        "monthlySubWithPrice": "Full access, billed monthly ({{price}})",
        "lifetimeTitle": "Pro Lifetime",
        "lifetimeSubWithPrice": "Pay once, own it forever ({{price}})",
        "lifetimePaidOff": "paid off in 1 yr",
        "oneTimePayment": "One-time payment",
        "hideOtherOptions": "Hide Other Options",
        "seeOtherOptions": "See Other Options",
        "includedInTrial": "Included in your trial:",
        "priceCompTitle": "Peak biology & mind for less than a daily treat",
        "gelato": "Gelato",
        "pint": "Pint",
        "bluomPro": "Bluom Pro",
        "restoring": "Restoring…",
        "restorePurchases": "Restore Purchases",
        "terms": "Terms",
        "privacy": "Privacy",
        "startTrialAndContinue": "Start Free Trial & Continue",
        "getLifetimeAccess": "Get Lifetime Access",
        "subscribeMonthly": "Subscribe Monthly",
        "noCommitment": "No commitment · Cancel anytime in Settings",
        "defaultTrialText": "7-day free trial",
        "unavailableTitle": "Unavailable",
        "unavailableMsg": "Please check your connection and try again.",
        "welcomeProTitle": "Welcome to Pro ✦",
        "welcomeProMsg": "Your trial is active. Full access is unlocked!",
        "purchaseFailedTitle": "Purchase failed",
        "pleaseTryAgain": "Please try again.",
        "restoredTitle": "Restored ✦",
        "restoredMsg": "Pro access has been restored.",
        "nothingToRestoreTitle": "Nothing to restore",
        "nothingToRestoreMsg": "No active Pro purchase found.",
        "restoreFailedTitle": "Restore failed",
        "featNutritionTitle": "Personalised Nutrition Plan",
        "featNutritionDesc": "Custom macros, meals and daily protocols tailored to your goals",
        "featFitnessTitle": "Personalised Fitness Plan",
        "featFitnessDesc": "4-week progressive training programme built around your schedule",
        "featMentalTitle": "Mental Health Plan",
        "featMentalDesc": "Weekly mindset themes, stress protocols and meditation sessions",
        "featWomensHealthTitle": "Women's Health Optimisation",
        "featWomensHealthDesc": "Cycle tracking, phase-based protocols and pregnancy support",
        "featMensHealthTitle": "Men's Health Optimisation",
        "featMensHealthDesc": "Testosterone protocols and male performance tracking",
        "featProductivityTitle": "Productivity Tools",
        "featProductivityDesc": "Deep work timers, focus states and schedule planners",
        "featHabitsTitle": "Habits Tracker",
        "featHabitsDesc": "Daily habit tracking and streak builder",
        "featSleepTitle": "Sleep Analysis",
        "featSleepDesc": "Sleep protocols and circadian rhythm optimisation",
        "featAiCoachTitle": "AI Coach",
        "featAiCoachDesc": "Unlimited personalised responses",
        "featVisionTitle": "AI Vision",
        "featVisionDesc": "Scan meals with your camera",
        "featAnalyticsTitle": "Advanced Analytics",
        "featAnalyticsDesc": "Deep health and performance trends"
    },
    "es": {
        "title": "Bluom Pro",
        "subtitle": "Libera todo tu potencial",
        "bestValue": "★ MEJOR VALOR",
        "alreadyPro": "✦ Ya eres Pro",
        "alreadyProSub": "El acceso completo está activo. Sigue optimizando.",
        "continue": "Continuar",
        "trialHeader": "Así funciona tu prueba gratuita",
        "step1Title": "Hoy: Inicia tu prueba gratuita",
        "step1Sub": "Acceso instantáneo e ilimitado a escaneos de comidas con IA, entrenamientos, salud mental y ciclo.",
        "step2Title": "Día 5: Recordatorio de prueba ({{date}})",
        "step2Sub": "Recibirás una notificación y un correo recordando que tu prueba gratuita terminará pronto.",
        "step3Title": "Día 7: Fin de la prueba ({{date}})",
        "step3Sub": "Se te cobrará el plan seleccionado. Cancela en cualquier momento en los ajustes de la tienda.",
        "annualTitle": "Pro Anual",
        "annualSubWithPrice": "Facturado anualmente ({{price}})",
        "perYear": "/ año",
        "perMonth": "/ mes",
        "perWeek": "/sem",
        "monthlyTitle": "Pro Mensual",
        "monthlySubWithPrice": "Acceso total, facturado mensualmente ({{price}})",
        "lifetimeTitle": "Pro Vitalicio",
        "lifetimeSubWithPrice": "Paga una vez, tuyo para siempre ({{price}})",
        "lifetimePaidOff": "amortizado en 1 año",
        "oneTimePayment": "Pago único",
        "hideOtherOptions": "Ocultar otras opciones",
        "seeOtherOptions": "Ver otras opciones",
        "includedInTrial": "Incluido en tu prueba:",
        "priceCompTitle": "Biología y mente óptimas por menos que un capricho diario",
        "gelato": "Helado",
        "pint": "Cerveza",
        "bluomPro": "Bluom Pro",
        "restoring": "Restaurando…",
        "restorePurchases": "Restaurar compras",
        "terms": "Términos",
        "privacy": "Privacidad",
        "startTrialAndContinue": "Comenzar prueba gratis y continuar",
        "getLifetimeAccess": "Obtener acceso vitalicio",
        "subscribeMonthly": "Suscribirse mensualmente",
        "noCommitment": "Sin permanencia · Cancela cuando quieras en Ajustes",
        "defaultTrialText": "7 días de prueba gratis",
        "unavailableTitle": "No disponible",
        "unavailableMsg": "Comprueba tu conexión e inténtalo de nuevo.",
        "welcomeProTitle": "¡Bienvenido a Pro ✦!",
        "welcomeProMsg": "Tu prueba está activa. ¡Acceso total desbloqueado!",
        "purchaseFailedTitle": "Error en la compra",
        "pleaseTryAgain": "Por favor, inténtalo de nuevo.",
        "restoredTitle": "Restaurado ✦",
        "restoredMsg": "Tu acceso Pro ha sido restaurado.",
        "nothingToRestoreTitle": "Nada que restaurar",
        "nothingToRestoreMsg": "No se encontró ninguna compra Pro activa.",
        "restoreFailedTitle": "Error al restaurar",
        "featNutritionTitle": "Plan de nutrición personalizado",
        "featNutritionDesc": "Macros a medida, comidas y protocolos según tus objetivos",
        "featFitnessTitle": "Plan de entrenamiento personalizado",
        "featFitnessDesc": "Programa progresivo de 4 semanas adaptado a tu horario",
        "featMentalTitle": "Plan de salud mental",
        "featMentalDesc": "Temas semanales, protocolos antiestrés y meditaciones",
        "featWomensHealthTitle": "Salud femenina avanzada",
        "featWomensHealthDesc": "Seguimiento del ciclo, fases hormonales y soporte de embarazo",
        "featMensHealthTitle": "Salud masculina y rendimiento",
        "featMensHealthDesc": "Protocolos de testosterona y rendimiento físico",
        "featProductivityTitle": "Herramientas de productividad",
        "featProductivityDesc": "Temporizadores de enfoque profundo y planificación diaria",
        "featHabitsTitle": "Seguimiento de hábitos",
        "featHabitsDesc": "Construye hábitos y mantén tus rachas diarias",
        "featSleepTitle": "Análisis del sueño",
        "featSleepDesc": "Protocolos de descanso y optimización circadiana",
        "featAiCoachTitle": "Coach IA dedicado",
        "featAiCoachDesc": "Respuestas y asesoría personalizada ilimitada",
        "featVisionTitle": "Visión por IA",
        "featVisionDesc": "Escanea comidas instantáneamente con tu cámara",
        "featAnalyticsTitle": "Analítica avanzada",
        "featAnalyticsDesc": "Tendencias profundas de salud y rendimiento"
    },
    "pt": {
        "title": "Bluom Pro",
        "subtitle": "Desbloqueie todo o seu potencial",
        "bestValue": "★ MELHOR VALOR",
        "alreadyPro": "✦ Você é Pro",
        "alreadyProSub": "Acesso total ativo. Continue a otimizar.",
        "continue": "Continuar",
        "trialHeader": "Como funciona o seu teste gratuito",
        "step1Title": "Hoje: Comece o seu teste gratuito",
        "step1Sub": "Acesso instantâneo e ilimitado a análise de refeições por IA, treinos, saúde mental e ciclo.",
        "step2Title": "Dia 5: Lembrete do teste ({{date}})",
        "step2Sub": "Receberá uma notificação e email a lembrar que o seu teste terminará em breve.",
        "step3Title": "Dia 7: Fim do teste ({{date}})",
        "step3Sub": "O plano escolhido será faturado. Cancele quando quiser nas definições da loja.",
        "annualTitle": "Pro Anual",
        "annualSubWithPrice": "Faturado anualmente ({{price}})",
        "perYear": "/ ano",
        "perMonth": "/ mês",
        "perWeek": "/sem",
        "monthlyTitle": "Pro Mensal",
        "monthlySubWithPrice": "Acesso total, faturado mensalmente ({{price}})",
        "lifetimeTitle": "Pro Vitalício",
        "lifetimeSubWithPrice": "Pague uma vez, seu para sempre ({{price}})",
        "lifetimePaidOff": "amortizado em 1 ano",
        "oneTimePayment": "Pagamento único",
        "hideOtherOptions": "Ocultar outras opções",
        "seeOtherOptions": "Ver outras opções",
        "includedInTrial": "Incluído no seu teste:",
        "priceCompTitle": "Biologia e mente no auge por menos de um mimo diário",
        "gelato": "Gelado",
        "pint": "Cerveja",
        "bluomPro": "Bluom Pro",
        "restoring": "A restaurar…",
        "restorePurchases": "Restaurar compras",
        "terms": "Termos",
        "privacy": "Privacidade",
        "startTrialAndContinue": "Iniciar teste grátis e continuar",
        "getLifetimeAccess": "Obter acesso vitalício",
        "subscribeMonthly": "Subscrever mensalmente",
        "noCommitment": "Sem fidelização · Cancele quando quiser nas Definições",
        "defaultTrialText": "7 dias de teste grátis",
        "unavailableTitle": "Indisponível",
        "unavailableMsg": "Verifique a ligação à internet e tente novamente.",
        "welcomeProTitle": "Bem-vindo ao Pro ✦",
        "welcomeProMsg": "O seu teste está ativo. Acesso total desbloqueado!",
        "purchaseFailedTitle": "Falha na compra",
        "pleaseTryAgain": "Por favor, tente novamente.",
        "restoredTitle": "Restaurado ✦",
        "restoredMsg": "O seu acesso Pro foi restaurado.",
        "nothingToRestoreTitle": "Nada a restaurar",
        "nothingToRestoreMsg": "Nenhuma compra Pro ativa encontrada.",
        "restoreFailedTitle": "Falha no restauro",
        "featNutritionTitle": "Plano de nutrição personalizado",
        "featNutritionDesc": "Macros sob medida, refeições e protocolos adaptados aos seus objetivos",
        "featFitnessTitle": "Plano de treino personalizado",
        "featFitnessDesc": "Programa progressivo de 4 semanas ajustado à sua rotina",
        "featMentalTitle": "Plano de saúde mental",
        "featMentalDesc": "Temas semanais, protocolos anti-stress e meditação",
        "featWomensHealthTitle": "Otimização da saúde feminina",
        "featWomensHealthDesc": "Registo do ciclo, fases hormonais e apoio na gravidez",
        "featMensHealthTitle": "Otimização da saúde masculina",
        "featMensHealthDesc": "Protocolos de testosterona e desempenho masculino",
        "featProductivityTitle": "Ferramentas de produtividade",
        "featProductivityDesc": "Cronómetros de foco profundo e planeamento de rotinas",
        "featHabitsTitle": "Rastreador de hábitos",
        "featHabitsDesc": "Acompanhamento diário e construção de sequências",
        "featSleepTitle": "Análise do sono",
        "featSleepDesc": "Protocolos de descanso e ritmo circadiano",
        "featAiCoachTitle": "Treinador IA",
        "featAiCoachDesc": "Respostas e acompanhamento personalizado ilimitado",
        "featVisionTitle": "Visão por IA",
        "featVisionDesc": "Digitalize refeições usando a câmara",
        "featAnalyticsTitle": "Estatísticas avançadas",
        "featAnalyticsDesc": "Tendências detalhadas de saúde e rendimento"
    },
    "de": {
        "title": "Bluom Pro",
        "subtitle": "Schöpfen Sie Ihr volles Potenzial aus",
        "bestValue": "★ BESTER WERT",
        "alreadyPro": "✦ Sie sind Pro",
        "alreadyProSub": "Voller Zugriff aktiv. Optimieren Sie weiter.",
        "continue": "Weiter",
        "trialHeader": "So funktioniert Ihre kostenlose Testphase",
        "step1Title": "Heute: Kostenlose Testphase starten",
        "step1Sub": "Sofortiger unbegrenzter Zugriff auf KI-Mahlzeitenscans, Workouts, mentale Gesundheit & Zyklusprotokolle.",
        "step2Title": "Tag 5: Erinnerung an die Testphase ({{date}})",
        "step2Sub": "Sie erhalten eine Benachrichtigung und E-Mail, dass Ihre Testphase bald endet.",
        "step3Title": "Tag 7: Testphase endet ({{date}})",
        "step3Sub": "Der gewählte Tarif wird abgebucht. Jederzeit vorab in den Store-Einstellungen kündbar.",
        "annualTitle": "Pro Jahresabo",
        "annualSubWithPrice": "Jährlich abgerechnet ({{price}})",
        "perYear": "/ Jahr",
        "perMonth": "/ Monat",
        "perWeek": "/Woche",
        "monthlyTitle": "Pro Monatsabo",
        "monthlySubWithPrice": "Voller Zugriff, monatlich abgerechnet ({{price}})",
        "lifetimeTitle": "Pro Lifetime",
        "lifetimeSubWithPrice": "Einmal zahlen, für immer besitzen ({{price}})",
        "lifetimePaidOff": "in 1 Jahr amortisiert",
        "oneTimePayment": "Einmalige Zahlung",
        "hideOtherOptions": "Andere Optionen ausblenden",
        "seeOtherOptions": "Andere Optionen anzeigen",
        "includedInTrial": "In Ihrer Testphase enthalten:",
        "priceCompTitle": "Spitzenbiologie & Fokus für weniger als ein täglicher Snack",
        "gelato": "Eis",
        "pint": "Bier",
        "bluomPro": "Bluom Pro",
        "restoring": "Wiederherstellung…",
        "restorePurchases": "Käufe wiederherstellen",
        "terms": "AGB",
        "privacy": "Datenschutz",
        "startTrialAndContinue": "Gratis testen & fortfahren",
        "getLifetimeAccess": "Lebenslangen Zugang sichern",
        "subscribeMonthly": "Monatlich abonnieren",
        "noCommitment": "Keine Verpflichtung · Jederzeit in den Einstellungen kündbar",
        "defaultTrialText": "7 Tage kostenlos testen",
        "unavailableTitle": "Nicht verfügbar",
        "unavailableMsg": "Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.",
        "welcomeProTitle": "Willkommen bei Pro ✦",
        "welcomeProMsg": "Ihre Testphase ist aktiv. Voller Zugriff freigeschaltet!",
        "purchaseFailedTitle": "Kauf fehlgeschlagen",
        "pleaseTryAgain": "Bitte versuchen Sie es erneut.",
        "restoredTitle": "Wiederhergestellt ✦",
        "restoredMsg": "Ihr Pro-Zugang wurde wiederhergestellt.",
        "nothingToRestoreTitle": "Nichts wiederherzustellen",
        "nothingToRestoreMsg": "Kein aktiver Pro-Kauf gefunden.",
        "restoreFailedTitle": "Wiederherstellung fehlgeschlagen",
        "featNutritionTitle": "Personalisierter Ernährungsplan",
        "featNutritionDesc": "Individuelle Makros, Mahlzeiten und Tagesprotokolle",
        "featFitnessTitle": "Personalisierter Trainingsplan",
        "featFitnessDesc": "4-wöchiges progressives Programm abgestimmt auf Ihren Zeitplan",
        "featMentalTitle": "Mentale Gesundheit & Mindset",
        "featMentalDesc": "Wöchentliche Themen, Stressabbau und geführte Meditationen",
        "featWomensHealthTitle": "Frauengesundheit & Zyklus",
        "featWomensHealthDesc": "Zyklus-Tracking, hormonelle Phasen und Schwangerschaftsbegleitung",
        "featMensHealthTitle": "Männergesundheit & Vitalität",
        "featMensHealthDesc": "Testosteron-Optimierung und Leistungsprotokolle",
        "featProductivityTitle": "Produktivitäts-Tools",
        "featProductivityDesc": "Deep-Work-Timer, Fokusphasen und Tagesplaner",
        "featHabitsTitle": "Gewohnheits-Tracker",
        "featHabitsDesc": "Tägliche Routinen aufbauen und Serien halten",
        "featSleepTitle": "Schlafanalyse",
        "featSleepDesc": "Schlafprotokolle und Optimierung des zirkadianen Rhythmus",
        "featAiCoachTitle": "Persönlicher KI-Coach",
        "featAiCoachDesc": "Unbegrenzte personalisierte Antworten und Beratung",
        "featVisionTitle": "KI-Mahlzeitenscan",
        "featVisionDesc": "Mahlzeiten sofort mit der Kamera analysieren",
        "featAnalyticsTitle": "Erweiterte Analysen",
        "featAnalyticsDesc": "Tiefgehende Gesundheits- und Leistungstrends"
    },
    "fr": {
        "title": "Bluom Pro",
        "subtitle": "Libérez tout votre potentiel",
        "bestValue": "★ MEILLEURE OFFRE",
        "alreadyPro": "✦ Vous êtes Pro",
        "alreadyProSub": "Accès complet actif. Continuez à optimiser.",
        "continue": "Continuer",
        "trialHeader": "Comment fonctionne votre essai gratuit",
        "step1Title": "Aujourd'hui : Démarrez votre essai gratuit",
        "step1Sub": "Accès instantané et illimité aux scans de repas par IA, entraînements, santé mentale et cycle.",
        "step2Title": "Jour 5 : Rappel de fin d'essai ({{date}})",
        "step2Sub": "Vous recevrez une notification et un e-mail pour vous rappeler que votre essai se termine bientôt.",
        "step3Title": "Jour 7 : Fin de l'essai ({{date}})",
        "step3Sub": "Vous serez facturé selon le forfait choisi. Annulez à tout moment dans les réglages du Store.",
        "annualTitle": "Pro Annuel",
        "annualSubWithPrice": "Facturé annuellement ({{price}})",
        "perYear": "/ an",
        "perMonth": "/ mois",
        "perWeek": "/sem",
        "monthlyTitle": "Pro Mensuel",
        "monthlySubWithPrice": "Accès complet, facturé chaque mois ({{price}})",
        "lifetimeTitle": "Pro À Vie",
        "lifetimeSubWithPrice": "Payez une fois, profitez-en pour toujours ({{price}})",
        "lifetimePaidOff": "rentabilisé en 1 an",
        "oneTimePayment": "Paiement unique",
        "hideOtherOptions": "Masquer les autres options",
        "seeOtherOptions": "Voir d'autres options",
        "includedInTrial": "Inclus dans votre essai :",
        "priceCompTitle": "Biologie et esprit au sommet pour moins qu'un plaisir quotidien",
        "gelato": "Glace",
        "pint": "Bière",
        "bluomPro": "Bluom Pro",
        "restoring": "Restauration…",
        "restorePurchases": "Restaurer les achats",
        "terms": "Conditions",
        "privacy": "Confidentialité",
        "startTrialAndContinue": "Démarrer l'essai gratuit & Continuer",
        "getLifetimeAccess": "Obtenir l'accès à vie",
        "subscribeMonthly": "S'abonner mensuellement",
        "noCommitment": "Sans engagement · Annulez à tout moment dans Réglages",
        "defaultTrialText": "7 jours d'essai gratuit",
        "unavailableTitle": "Indisponible",
        "unavailableMsg": "Vérifiez votre connexion internet et réessayez.",
        "welcomeProTitle": "Bienvenue sur Pro ✦",
        "welcomeProMsg": "Votre essai est actif. L'accès complet est déverrouillé !",
        "purchaseFailedTitle": "Échec de l'achat",
        "pleaseTryAgain": "Veuillez réessayer.",
        "restoredTitle": "Restauré ✦",
        "restoredMsg": "Votre accès Pro a été restauré.",
        "nothingToRestoreTitle": "Rien à restaurar",
        "nothingToRestoreMsg": "Aucun achat Pro actif trouvé.",
        "restoreFailedTitle": "Échec de la restauration",
        "featNutritionTitle": "Plan nutritionnel personnalisé",
        "featNutritionDesc": "Macros sur mesure, repas et protocoles quotidiens",
        "featFitnessTitle": "Plan d'entraînement sur mesure",
        "featFitnessDesc": "Programme progressif sur 4 semaines adapté à votre emploi du temps",
        "featMentalTitle": "Plan de santé mentale",
        "featMentalDesc": "Thèmes hebdomadaires, protocoles anti-stress et méditations",
        "featWomensHealthTitle": "Santé féminine & Cycle",
        "featWomensHealthDesc": "Suivi du cycle, phases hormonales et accompagnement grossesse",
        "featMensHealthTitle": "Santé masculine & Vitalité",
        "featMensHealthDesc": "Protocoles de testostérone et suivi de performance",
        "featProductivityTitle": "Outils de productivité",
        "featProductivityDesc": "Minuteurs de concentration profonde et planification",
        "featHabitsTitle": "Suivi des habitudes",
        "featHabitsDesc": "Ancrez vos rituels quotidiens et développez vos séries",
        "featSleepTitle": "Analyse du sommeil",
        "featSleepDesc": "Protocoles de sommeil et rythme circadien",
        "featAiCoachTitle": "Coach IA dédié",
        "featAiCoachDesc": "Réponses et conseils personnalisés en illimité",
        "featVisionTitle": "Vision IA",
        "featVisionDesc": "Analysez vos repas instantanément avec l'appareil photo",
        "featAnalyticsTitle": "Analyses avancées",
        "featAnalyticsDesc": "Tendances approfondies sur votre santé et forme"
    },
    "it": {
        "title": "Bluom Pro",
        "subtitle": "Sblocca tutto il tuo potenziale",
        "bestValue": "★ MIGLIOR VALORE",
        "alreadyPro": "✦ Sei Pro",
        "alreadyProSub": "Accesso completo attivo. Continua a ottimizzare.",
        "continue": "Continua",
        "trialHeader": "Come funziona la tua prova gratuita",
        "step1Title": "Oggi: Inizia la prova gratuita",
        "step1Sub": "Accesso illimitato e immediato a scansione pasti con IA, workout, salute mentale e ciclo.",
        "step2Title": "Giorno 5: Promemoria prova ({{date}})",
        "step2Sub": "Riceverai una notifica e un'email che ti ricorderanno che la prova scadrà a breve.",
        "step3Title": "Giorno 7: Fine della prova ({{date}})",
        "step3Sub": "Ti verrà addebitato il piano scelto. Annulla in qualsiasi momento nelle impostazioni dello store.",
        "annualTitle": "Pro Annuale",
        "annualSubWithPrice": "Fatturato annualmente ({{price}})",
        "perYear": "/ anno",
        "perMonth": "/ mese",
        "perWeek": "/sett",
        "monthlyTitle": "Pro Mensile",
        "monthlySubWithPrice": "Accesso totale, fatturato mensilmente ({{price}})",
        "lifetimeTitle": "Pro A Vita",
        "lifetimeSubWithPrice": "Paga una volta, tuo per sempre ({{price}})",
        "lifetimePaidOff": "ammortizzato in 1 anno",
        "oneTimePayment": "Pagamento una tantum",
        "hideOtherOptions": "Nascondi altre opzioni",
        "seeOtherOptions": "Mostra altre opzioni",
        "includedInTrial": "Incluso nella tua prova:",
        "priceCompTitle": "Massima biologia e mente al prezzo di un piccolo piacere al giorno",
        "gelato": "Gelato",
        "pint": "Birra",
        "bluomPro": "Bluom Pro",
        "restoring": "Ripristino…",
        "restorePurchases": "Ripristina acquisti",
        "terms": "Termini",
        "privacy": "Privacy",
        "startTrialAndContinue": "Inizia la prova gratis e continua",
        "getLifetimeAccess": "Ottieni accesso a vita",
        "subscribeMonthly": "Abbonati mensilmente",
        "noCommitment": "Nessun vincolo · Annulla quando vuoi nelle Impostazioni",
        "defaultTrialText": "7 giorni di prova gratuita",
        "unavailableTitle": "Non disponibile",
        "unavailableMsg": "Verifica la tua connessione e riprova.",
        "welcomeProTitle": "Benvenuto in Pro ✦",
        "welcomeProMsg": "La tua prova è attiva. Accesso totale sbloccato!",
        "purchaseFailedTitle": "Acquisto non riuscito",
        "pleaseTryAgain": "Per favore riprova.",
        "restoredTitle": "Ripristinato ✦",
        "restoredMsg": "Il tuo accesso Pro è stato ripristinato.",
        "nothingToRestoreTitle": "Niente da ripristinare",
        "nothingToRestoreMsg": "Nessun acquisto Pro attivo trovato.",
        "restoreFailedTitle": "Ripristino fallito",
        "featNutritionTitle": "Piano nutrizionale personalizzato",
        "featNutritionDesc": "Macro personalizzati, ricette e protocolli giornalieri",
        "featFitnessTitle": "Piano di allenamento su misura",
        "featFitnessDesc": "Programma progressivo di 4 settimane basato sui tuoi orari",
        "featMentalTitle": "Piano per la salute mentale",
        "featMentalDesc": "Temi settimanali, protocolli antistress e meditazioni",
        "featWomensHealthTitle": "Ottimizzazione salute femminile",
        "featWomensHealthDesc": "Monitoraggio del ciclo, fasi ormonali e supporto gravidanza",
        "featMensHealthTitle": "Ottimizzazione salute maschile",
        "featMensHealthDesc": "Protocolli per testosterone e prestazioni maschili",
        "featProductivityTitle": "Strumenti di produttività",
        "featProductivityDesc": "Timer deep work, modalità focus e pianificazione",
        "featHabitsTitle": "Monitoraggio abitudini",
        "featHabitsDesc": "Traccia le tue abitudini e crea serie continue",
        "featSleepTitle": "Analisi del sonno",
        "featSleepDesc": "Protocolli del sonno e sincronizzazione circadiana",
        "featAiCoachTitle": "Coach IA dedicato",
        "featAiCoachDesc": "Risposte e supporto personalizzato illimitati",
        "featVisionTitle": "Visione IA per pasti",
        "featVisionDesc": "Scansiona i pasti al volo con la fotocamera",
        "featAnalyticsTitle": "Analitica avanzata",
        "featAnalyticsDesc": "Trend approfonditi su salute e prestazioni"
    },
    "nl": {
        "title": "Bluom Pro",
        "subtitle": "Ontgrendel uw volledige potentieel",
        "bestValue": "★ BESTE WAARDE",
        "alreadyPro": "✦ U bent Pro",
        "alreadyProSub": "Volledige toegang is actief. Blijf optimaliseren.",
        "continue": "Doorgaan",
        "trialHeader": "Zo werkt uw gratis proefperiode",
        "step1Title": "Vandaag: Start uw gratis proefperiode",
        "step1Sub": "Direct onbeperkt toegang tot AI-maaltijdscans, workouts, mentale gezondheid & cyclusinzichten.",
        "step2Title": "Dag 5: Proefperiode herinnering ({{date}})",
        "step2Sub": "U ontvangt een melding en e-mail dat uw proefperiode binnenkort afloopt.",
        "step3Title": "Dag 7: Proefperiode eindigt ({{date}})",
        "step3Sub": "Het gekozen abonnement wordt in rekening gebracht. Altijd opzegbaar in de Store-instellingen.",
        "annualTitle": "Pro Jaarabonnement",
        "annualSubWithPrice": "Jaarlijks gefactureerd ({{price}})",
        "perYear": "/ jaar",
        "perMonth": "/ mnd",
        "perWeek": "/wk",
        "monthlyTitle": "Pro Maandabonnement",
        "monthlySubWithPrice": "Volledige toegang, maandelijks gefactureerd ({{price}})",
        "lifetimeTitle": "Pro Levenslang",
        "lifetimeSubWithPrice": "Eenmalig betalen, voor altijd toegang ({{price}})",
        "lifetimePaidOff": "terugverdiend in 1 jr",
        "oneTimePayment": "Eenmalige betaling",
        "hideOtherOptions": "Verberg andere opties",
        "seeOtherOptions": "Bekijk andere opties",
        "includedInTrial": "Inbegrepen in uw proefperiode:",
        "priceCompTitle": "Topprestaties voor minder dan een dagelijkse traktatie",
        "gelato": "IJsje",
        "pint": "Biertje",
        "bluomPro": "Bluom Pro",
        "restoring": "Herstellen…",
        "restorePurchases": "Aankopen herstellen",
        "terms": "Voorwaarden",
        "privacy": "Privacy",
        "startTrialAndContinue": "Gratis proberen & Doorgaan",
        "getLifetimeAccess": "Krijg levenslange toegang",
        "subscribeMonthly": "Maandelijks abonneren",
        "noCommitment": "Geen verplichtingen · Altijd opzegbaar via Instellingen",
        "defaultTrialText": "7 dagen gratis proefperiode",
        "unavailableTitle": "Niet beschikbaar",
        "unavailableMsg": "Controleer uw internetverbinding en probeer het opnieuw.",
        "welcomeProTitle": "Welkom bij Pro ✦",
        "welcomeProMsg": "Uw proefperiode is geactiveerd. Volledige toegang ontgrendeld!",
        "purchaseFailedTitle": "Aankoop mislukt",
        "pleaseTryAgain": "Probeer het opnieuw.",
        "restoredTitle": "Hersteld ✦",
        "restoredMsg": "Uw Pro-toegang is succesvol hersteld.",
        "nothingToRestoreTitle": "Niets te herstellen",
        "nothingToRestoreMsg": "Geen actieve Pro-aankoop gevonden.",
        "restoreFailedTitle": "Herstellen mislukt",
        "featNutritionTitle": "Gepersonaliseerd voedingsplan",
        "featNutritionDesc": "Aangepaste macro's, maaltijden en dagelijkse protocollen",
        "featFitnessTitle": "Gepersonaliseerd fitnessplan",
        "featFitnessDesc": "Progressief trainingsprogramma van 4 weken op uw tempo",
        "featMentalTitle": "Mentaal welzijnsplan",
        "featMentalDesc": "Wekelijkse thema's, stressprotocollen en meditaties",
        "featWomensHealthTitle": "Gezondheid van de vrouw",
        "featWomensHealthDesc": "Cyclusregistratie, hormonale fasen en zwangerschapsondersteuning",
        "featMensHealthTitle": "Gezondheid van de man",
        "featMensHealthDesc": "Testosteronprotocollen en prestatieverbetering",
        "featProductivityTitle": "Productiviteitstools",
        "featProductivityDesc": "Focus-timers voor deep work en dagelijkse planners",
        "featHabitsTitle": "Gewoonten-tracker",
        "featHabitsDesc": "Bouw dagelijkse gewoonten op en behoud uw streak",
        "featSleepTitle": "Slaapanalyse",
        "featSleepDesc": "Slaapprotocollen en circadiane ritme-optimalisatie",
        "featAiCoachTitle": "Toegewijde AI-coach",
        "featAiCoachDesc": "Onbeperkt persoonlijke adviezen en antwoorden",
        "featVisionTitle": "AI Maaltijdscanner",
        "featVisionDesc": "Scan maaltijden direct met uw camera",
        "featAnalyticsTitle": "Geavanceerde statistieken",
        "featAnalyticsDesc": "Diepgaande inzichten in gezondheid en trends"
    },
    "da": {
        "title": "Bluom Pro",
        "subtitle": "Frigør dit fulde potentiale",
        "bestValue": "★ BEDSTE VÆRDI",
        "alreadyPro": "✦ Du er Pro",
        "alreadyProSub": "Fuld adgang er aktiv. Fortsæt med at optimere.",
        "continue": "Fortsæt",
        "trialHeader": "Sådan fungerer din gratis prøveperiode",
        "step1Title": "I dag: Start din gratis prøveperiode",
        "step1Sub": "Få øjeblikkelig adgang til ubegrænsede AI-måltidsscanninger, træningsprogrammer og cyklusindsigt.",
        "step2Title": "Dag 5: Prøvepåmindelse ({{date}})",
        "step2Sub": "Du modtager en besked og e-mail om, at din prøveperiode snart udløber.",
        "step3Title": "Dag 7: Prøveperioden slutter ({{date}})",
        "step3Sub": "Det valgte abonnement trækkes. Opsig når som helst i butikkens indstillinger.",
        "annualTitle": "Pro Årlig",
        "annualSubWithPrice": "Faktureres årligt ({{price}})",
        "perYear": "/ år",
        "perMonth": "/ md",
        "perWeek": "/uge",
        "monthlyTitle": "Pro Månedlig",
        "monthlySubWithPrice": "Fuld adgang, faktureres månedligt ({{price}})",
        "lifetimeTitle": "Pro Livstid",
        "lifetimeSubWithPrice": "Betal én gang, ej det for evigt ({{price}})",
        "lifetimePaidOff": "tjent ind på 1 år",
        "oneTimePayment": "Engangsbetaling",
        "hideOtherOptions": "Skjul andre muligheder",
        "seeOtherOptions": "Se andre muligheder",
        "includedInTrial": "Inkluderet i din prøveperiode:",
        "priceCompTitle": "Maksimal biologi & fokus for mindre end en daglig snack",
        "gelato": "Is",
        "pint": "Øl",
        "bluomPro": "Bluom Pro",
        "restoring": "Gendanner…",
        "restorePurchases": "Gendan køb",
        "terms": "Vilkår",
        "privacy": "Privatliv",
        "startTrialAndContinue": "Start gratis prøve & Fortsæt",
        "getLifetimeAccess": "Få livstidsadgang",
        "subscribeMonthly": "Abonner månedligt",
        "noCommitment": "Ingen binding · Opsig når som helst i Indstillinger",
        "defaultTrialText": "7 dages gratis prøveperiode",
        "unavailableTitle": "Utilgængelig",
        "unavailableMsg": "Tjek venligst din internetforbindelse og prøv igen.",
        "welcomeProTitle": "Velkommen til Pro ✦",
        "welcomeProMsg": "Din prøveperiode er i gang. Fuld adgang låst op!",
        "purchaseFailedTitle": "Køb mislykkedes",
        "pleaseTryAgain": "Prøv venligst igen.",
        "restoredTitle": "Gendannet ✦",
        "restoredMsg": "Din Pro-adgang er blevet gendannet.",
        "nothingToRestoreTitle": "Intet at gendanne",
        "nothingToRestoreMsg": "Der blev ikke fundet noget aktivt Pro-køb.",
        "restoreFailedTitle": "Gendannelse mislykkedes",
        "featNutritionTitle": "Personlig kostplan",
        "featNutritionDesc": "Tilpassede makrotal, måltider og daglige protokoller",
        "featFitnessTitle": "Personlig træningsplan",
        "featFitnessDesc": "4-ugers progressivt program bygget omkring din tidsplan",
        "featMentalTitle": "Mental sundhedsplan",
        "featMentalDesc": "Ugentlige temaer, stresshåndtering og guidede meditationer",
        "featWomensHealthTitle": "Kvinders sundhed & cyklus",
        "featWomensHealthDesc": "Cyklussporing, hormonfaser og graviditetsstøtte",
        "featMensHealthTitle": "Mænds sundhed & vitalitet",
        "featMensHealthDesc": "Testosteronprotokoller og præstationssporing",
        "featProductivityTitle": "Produktivitetsværktøjer",
        "featProductivityDesc": "Fokus-timere til fordybelse og dagsplanlæggere",
        "featHabitsTitle": "Vane-tracker",
        "featHabitsDesc": "Opbyg sunde vaner og hold dine streaks",
        "featSleepTitle": "Søvnanalyse",
        "featSleepDesc": "Søvnprotokoller og døgnrytme-optimering",
        "featAiCoachTitle": "Dedikeret AI-coach",
        "featAiCoachDesc": "Ubegrænset personlig rådgivning og svar",
        "featVisionTitle": "AI Mad-scanner",
        "featVisionDesc": "Scan dine måltider øjeblikkeligt med kameraet",
        "featAnalyticsTitle": "Avanceret analyse",
        "featAnalyticsDesc": "Dybdegående sundheds- og præstationstendenser"
    },
    "sv": {
        "title": "Bluom Pro",
        "subtitle": "Nå din fulla potential",
        "bestValue": "★ BÄSTA VÄRDE",
        "alreadyPro": "✦ Du är Pro",
        "alreadyProSub": "Full tillgång är aktiv. Fortsätt att optimera.",
        "continue": "Fortsätt",
        "trialHeader": "Så fungerar din kostnadsfria provperiod",
        "step1Title": "Idag: Starta din gratis provperiod",
        "step1Sub": "Få omedelbar tillgång till obegränsade AI-måltidsscanningar, träningspass och cykelinsikter.",
        "step2Title": "Dag 5: Påminnelse om provperiod ({{date}})",
        "step2Sub": "Du får en notis och ett e-postmeddelande om att provperioden snart tar slut.",
        "step3Title": "Dag 7: Provperioden avslutas ({{date}})",
        "step3Sub": "Den valda planen debiteras. Avsluta när som helst före i Butiksinställningarna.",
        "annualTitle": "Pro Årlig",
        "annualSubWithPrice": "Faktureras årligen ({{price}})",
        "perYear": "/ år",
        "perMonth": "/ mån",
        "perWeek": "/vecka",
        "monthlyTitle": "Pro Månadsvis",
        "monthlySubWithPrice": "Full tillgång, faktureras månadsvis ({{price}})",
        "lifetimeTitle": "Pro Livstid",
        "lifetimeSubWithPrice": "Betala en gång, äg för alltid ({{price}})",
        "lifetimePaidOff": "återbetald på 1 år",
        "oneTimePayment": "Engångsbetalning",
        "hideOtherOptions": "Dölj andra alternativ",
        "seeOtherOptions": "Se andra alternativ",
        "includedInTrial": "Ingår i din provperiod:",
        "priceCompTitle": "Maximerad biologi och fokus för mindre än ett dagligt fika",
        "gelato": "Glass",
        "pint": "Öl",
        "bluomPro": "Bluom Pro",
        "restoring": "Återställer…",
        "restorePurchases": "Återställ köp",
        "terms": "Villkor",
        "privacy": "Integritet",
        "startTrialAndContinue": "Starta gratis provperiod & Fortsätt",
        "getLifetimeAccess": "Få livstidsåtkomst",
        "subscribeMonthly": "Prenumerera månadsvis",
        "noCommitment": "Ingen bindningstid · Avsluta när som helst i Inställningar",
        "defaultTrialText": "7 dagars gratis provperiod",
        "unavailableTitle": "Ej tillgänglig",
        "unavailableMsg": "Kontrollera internetanslutningen och försök igen.",
        "welcomeProTitle": "Välkommen till Pro ✦",
        "welcomeProMsg": "Din provperiod är igång. Full tillgång har låsts upp!",
        "purchaseFailedTitle": "Köp misslyckades",
        "pleaseTryAgain": "Försök igen.",
        "restoredTitle": "Återställd ✦",
        "restoredMsg": "Din Pro-tillgång har återställts.",
        "nothingToRestoreTitle": "Inget att återställa",
        "nothingToRestoreMsg": "Inget aktivt Pro-köp hittades.",
        "restoreFailedTitle": "Återställning misslyckades",
        "featNutritionTitle": "Personlig kostplan",
        "featNutritionDesc": "Skräddarsydda makron, måltider och dagliga protokoll",
        "featFitnessTitle": "Personlig träningsplan",
        "featFitnessDesc": "4-veckors progressivt program anpassat efter ditt schema",
        "featMentalTitle": "Mental hälso- & fokusplan",
        "featMentalDesc": "Veckoteman, stressprotokoll och guidade meditationer",
        "featWomensHealthTitle": "Kvinnohälsa & cykel",
        "featWomensHealthDesc": "Cykelspårning, hormonella faser och graviditetsstöd",
        "featMensHealthTitle": "Mäns hälsa & prestation",
        "featMensHealthDesc": "Testosteronprotokoll och prestationsuppföljning",
        "featProductivityTitle": "Produktivitetsverktyg",
        "featProductivityDesc": "Fokustimers för djuparbete och dagsplanering",
        "featHabitsTitle": "Vane-tracker",
        "featHabitsDesc": "Bygg goda vanor och behåll dina sviter",
        "featSleepTitle": "Sömnanalys",
        "featSleepDesc": "Sömnprotokoll och dygnsrytmsoptimering",
        "featAiCoachTitle": "Personlig AI-coach",
        "featAiCoachDesc": "Obegränsade personliga svar och vägledning",
        "featVisionTitle": "AI Måltidsscanning",
        "featVisionDesc": "Scanna måltider direkt med kameran",
        "featAnalyticsTitle": "Avancerad analys",
        "featAnalyticsDesc": "Djupgående hälso- och prestationstrender"
    },
    "no": {
        "title": "Bluom Pro",
        "subtitle": "Nå ditt fulle potensial",
        "bestValue": "★ BESTE VERDI",
        "alreadyPro": "✦ Du er Pro",
        "alreadyProSub": "Full tilgang er aktiv. Fortsett å optimalisere.",
        "continue": "Fortsett",
        "trialHeader": "Slik fungerer din gratis prøveperiode",
        "step1Title": "I dag: Start din gratis prøveperiode",
        "step1Sub": "Få umiddelbar tilgang til ubegrensede AI-måltidsskanninger, treningsøkter og syklusinnsikt.",
        "step2Title": "Dag 5: Påminnelse om prøveperiode ({{date}})",
        "step2Sub": "Du mottar et varsel og e-post om at prøveperioden snart utløper.",
        "step3Title": "Dag 7: Prøveperioden avsluttes ({{date}})",
        "step3Sub": "Den valgte planen belastes. Avslutt når som helst i butikkinnstillingene.",
        "annualTitle": "Pro Årlig",
        "annualSubWithPrice": "Faktureres årlig ({{price}})",
        "perYear": "/ år",
        "perMonth": "/ mnd",
        "perWeek": "/uke",
        "monthlyTitle": "Pro Månedlig",
        "monthlySubWithPrice": "Full tilgang, faktureres månedlig ({{price}})",
        "lifetimeTitle": "Pro Livstid",
        "lifetimeSubWithPrice": "Betal én gang, eier det for alltid ({{price}})",
        "lifetimePaidOff": "nedbetalt på 1 år",
        "oneTimePayment": "Engangsbetaling",
        "hideOtherOptions": "Skjul andre alternativer",
        "seeOtherOptions": "Se andre alternativer",
        "includedInTrial": "Inkludert i prøveperioden:",
        "priceCompTitle": "Topp biologi og fokus for mindre enn en daglig snack",
        "gelato": "Iskrem",
        "pint": "Øl",
        "bluomPro": "Bluom Pro",
        "restoring": "Gjenoppretter…",
        "restorePurchases": "Gjenopprett kjøp",
        "terms": "Vilkår",
        "privacy": "Personvern",
        "startTrialAndContinue": "Start gratis prøve & Fortsett",
        "getLifetimeAccess": "Få livstidstilgang",
        "subscribeMonthly": "Abonner månedlig",
        "noCommitment": "Ingen binding · Avslutt når som helst i Innstillinger",
        "defaultTrialText": "7 dagers gratis prøveperiode",
        "unavailableTitle": "Utilgjengelig",
        "unavailableMsg": "Sjekk internettforbindelsen din og prøv igjen.",
        "welcomeProTitle": "Velkommen til Pro ✦",
        "welcomeProMsg": "Prøveperioden er i gang. Full tilgang låst opp!",
        "purchaseFailedTitle": "Kjøp mislyktes",
        "pleaseTryAgain": "Vennligst prøv igjen.",
        "restoredTitle": "Gjenopprettet ✦",
        "restoredMsg": "Din Pro-tilgang er gjenopprettet.",
        "nothingToRestoreTitle": "Ingen kjøp å gjenopprette",
        "nothingToRestoreMsg": "Ingen aktive Pro-kjøp funnet.",
        "restoreFailedTitle": "Gjenoppretting mislyktes",
        "featNutritionTitle": "Personlig ernæringsplan",
        "featNutritionDesc": "Skreddersydde makroer, måltider og daglige protokoller",
        "featFitnessTitle": "Personlig treningsplan",
        "featFitnessDesc": "4-ukers progressivt program tilpasset timeplanen din",
        "featMentalTitle": "Mental helseplan",
        "featMentalDesc": "Ukentlige temaer, stressmestring og veiledede meditasjoner",
        "featWomensHealthTitle": "Kvinnehelse & syklus",
        "featWomensHealthDesc": "Syklussporing, hormonelle faser og graviditetsstøtte",
        "featMensHealthTitle": "Menns helse & ytelse",
        "featMensHealthDesc": "Testosteronprotokoller og prestasjonssporing",
        "featProductivityTitle": "Produktivitetsverktøy",
        "featProductivityDesc": "Fokustimere for dypjobbing og dagsplanlegging",
        "featHabitsTitle": "Vane-tracker",
        "featHabitsDesc": "Bygg gode vaner og oppretthold dine streaks",
        "featSleepTitle": "Søvnanalyse",
        "featSleepDesc": "Søvnprotokoller og døgnrytmeoptimalisering",
        "featAiCoachTitle": "Dedikert AI-coach",
        "featAiCoachDesc": "Ubegrenset personlig rådgivning og veiledning",
        "featVisionTitle": "AI Måltidsskanning",
        "featVisionDesc": "Skann måltider umiddelbart med kameraet",
        "featAnalyticsTitle": "Avanserte analyser",
        "featAnalyticsDesc": "Dypgående helse- og prestasjonstrender"
    },
    "fi": {
        "title": "Bluom Pro",
        "subtitle": "Avaa koko potentiaalisi",
        "bestValue": "★ PARAS ARVO",
        "alreadyPro": "✦ Olet Pro",
        "alreadyProSub": "Täysi käyttöoikeus on aktiivinen. Jatka optimointia.",
        "continue": "Jatka",
        "trialHeader": "Näin ilmainen kokeilusi toimii",
        "step1Title": "Tänään: Aloita ilmainen kokeilujakso",
        "step1Sub": "Hanki välitön pääsy rajoittamattomiin tekoäly-aterianskannauksiin, treeneihin ja syklinseurantaan.",
        "step2Title": "Päivä 5: Muistutus kokeilusta ({{date}})",
        "step2Sub": "Saat ilmoituksen ja sähköpostin siitä, että ilmainen kokeilusi päättyy pian.",
        "step3Title": "Päivä 7: Kokeilujakso päättyy ({{date}})",
        "step3Sub": "Valittu tilaus veloitetaan. Voit peruuttaa milloin tahansa sovelluskaupan asetuksista.",
        "annualTitle": "Pro Vuosijakso",
        "annualSubWithPrice": "Laskutetaan vuosittain ({{price}})",
        "perYear": "/ vuosi",
        "perMonth": "/ kk",
        "perWeek": "/vko",
        "monthlyTitle": "Pro Kuukausijakso",
        "monthlySubWithPrice": "Täysi pääsy, laskutetaan kuukausittain ({{price}})",
        "lifetimeTitle": "Pro Elinikäinen",
        "lifetimeSubWithPrice": "Maksa kerran, omista ikuisesti ({{price}})",
        "lifetimePaidOff": "maksaa itsensä takaisin 1 vuodessa",
        "oneTimePayment": "Kertamaksu",
        "hideOtherOptions": "Piilota muut vaihtoehdot",
        "seeOtherOptions": "Näytä muut vaihtoehdot",
        "includedInTrial": "Sisältyy kokeiluusi:",
        "priceCompTitle": "Huippubiologiaa ja mielenrauhaa alle päivittäisen herkun hinnalla",
        "gelato": "Jäätelö",
        "pint": "Tuoppi",
        "bluomPro": "Bluom Pro",
        "restoring": "Palautetaan…",
        "restorePurchases": "Palauta ostokset",
        "terms": "Ehdot",
        "privacy": "Tietosuoja",
        "startTrialAndContinue": "Aloita ilmainen kokeilu & Jatka",
        "getLifetimeAccess": "Hanki elinikäinen pääsy",
        "subscribeMonthly": "Tilaa kuukausittain",
        "noCommitment": "Ei sitoutumista · Peru milloin tahansa Asetuksista",
        "defaultTrialText": "7 päivän ilmainen kokeilu",
        "unavailableTitle": "Ei saatavilla",
        "unavailableMsg": "Tarkista internetyhteytesi ja yritä uudelleen.",
        "welcomeProTitle": "Tervetuloa Pro-jäseneksi ✦",
        "welcomeProMsg": "Kokeilusi on aktiivinen. Täysi pääsy avattu!",
        "purchaseFailedTitle": "Ostos epäonnistui",
        "pleaseTryAgain": "Yritä uudelleen.",
        "restoredTitle": "Palautettu ✦",
        "restoredMsg": "Pro-käyttöoikeutesi on palautettu.",
        "nothingToRestoreTitle": "Ei palautettavaa",
        "nothingToRestoreMsg": "Aktiivista Pro-tilausta ei löytynyt.",
        "restoreFailedTitle": "Palautus epäonnistui",
        "featNutritionTitle": "Yksilöllinen ravinto-ohjelma",
        "featNutritionDesc": "Räätälöidyt makrot, ateriat ja päivittäiset protokollat",
        "featFitnessTitle": "Yksilöllinen treeniohjelma",
        "featFitnessDesc": "4 viikon progressiivinen ohjelma aikatauluusi sovitettuna",
        "featMentalTitle": "Mielenterveysohjelma",
        "featMentalDesc": "Viikoittaiset teemat, stressinpurku ja meditaatiot",
        "featWomensHealthTitle": "Naisten terveyden optimointi",
        "featWomensHealthDesc": "Kierron seuranta, hormonivaiheet ja raskauden tuki",
        "featMensHealthTitle": "Miesten terveys & suorituskyky",
        "featMensHealthDesc": "Testosteroniprotokollat ja fyysisen suorituskyvyn seuranta",
        "featProductivityTitle": "Tuottavuustyökalut",
        "featProductivityDesc": "Syventymisajastimet ja päivittäinen suunnittelu",
        "featHabitsTitle": "Tapojen seuranta",
        "featHabitsDesc": "Rakenna päivittäisiä tapoja ja ylläpidä putkiasi",
        "featSleepTitle": "Unianalyysi",
        "featSleepDesc": "Uniprotokollat ja vuorokausirytmin optimointi",
        "featAiCoachTitle": "Oma AI-valmentaja",
        "featAiCoachDesc": "Rajoittamattomat personoidut vastaukset",
        "featVisionTitle": "AI-aterianskannaus",
        "featVisionDesc": "Skannaa ateriat kameralla silmänräpäyksessä",
        "featAnalyticsTitle": "Edistynyt analytiikka",
        "featAnalyticsDesc": "Syvälliset terveys- ja suorituskykytrendit"
    },
    "pl": {
        "title": "Bluom Pro",
        "subtitle": "Odblokuj swój pełny potencjał",
        "bestValue": "★ NAJLEPSZA OFERTA",
        "alreadyPro": "✦ Jesteś Pro",
        "alreadyProSub": "Pełny dostęp jest aktywny. Optymalizuj dalej.",
        "continue": "Kontynuuj",
        "trialHeader": "Jak działa Twój darmowy okres próbny",
        "step1Title": "Dziś: Rozpocznij darmowy okres próbny",
        "step1Sub": "Błyskawiczny dostęp do nielimitowanego skanowania posiłków AI, treningów i analizy cyklu.",
        "step2Title": "Dzień 5: Przypomnienie o okresie próbnym ({{date}})",
        "step2Sub": "Otrzymasz powiadomienie push i e-mail przypominający o zbliżającym się końcu okresu próbnego.",
        "step3Title": "Dzień 7: Koniec okresu próbnego ({{date}})",
        "step3Sub": "Zostaniesz obciążony opłatą za wybrany plan. Możesz anulować w dowolnym momencie w ustawieniach sklepu.",
        "annualTitle": "Pro Roczny",
        "annualSubWithPrice": "Rozliczany rocznie ({{price}})",
        "perYear": "/ rok",
        "perMonth": "/ mies.",
        "perWeek": "/tydz.",
        "monthlyTitle": "Pro Miesięczny",
        "monthlySubWithPrice": "Pełny dostęp, rozliczany miesięcznie ({{price}})",
        "lifetimeTitle": "Pro Dożywotni",
        "lifetimeSubWithPrice": "Płacisz raz, masz na zawsze ({{price}})",
        "lifetimePaidOff": "zwraca się w 1 rok",
        "oneTimePayment": "Płatność jednorazowa",
        "hideOtherOptions": "Ukryj inne opcje",
        "seeOtherOptions": "Zobacz inne opcje",
        "includedInTrial": "W cenie okresu próbnego:",
        "priceCompTitle": "Szczytowa biologia i umysł za mniej niż codzienna przekąska",
        "gelato": "Lody",
        "pint": "Piwo",
        "bluomPro": "Bluom Pro",
        "restoring": "Przywracanie…",
        "restorePurchases": "Przywróć zakupy",
        "terms": "Regulamin",
        "privacy": "Prywatność",
        "startTrialAndContinue": "Rozpocznij darmowy okres próbny i kontynuuj",
        "getLifetimeAccess": "Kup dostęp dożywotni",
        "subscribeMonthly": "Subskrybuj miesięcznie",
        "noCommitment": "Bez zobowiązań · Anuluj w dowolnej chwili w Ustawieniach",
        "defaultTrialText": "7 dni darmowego okresu próbnego",
        "unavailableTitle": "Niedostępne",
        "unavailableMsg": "Sprawdź połączenie z internetem i spróbuj ponownie.",
        "welcomeProTitle": "Witaj w Pro ✦",
        "welcomeProMsg": "Twój okres próbny jest aktywny. Odblokowano pełny dostęp!",
        "purchaseFailedTitle": "Zakup nie powiódł się",
        "pleaseTryAgain": "Spróbuj ponownie.",
        "restoredTitle": "Przywrócono ✦",
        "restoredMsg": "Twój dostęp Pro został przywrócony.",
        "nothingToRestoreTitle": "Brak zakupów do przywrócenia",
        "nothingToRestoreMsg": "Nie znaleziono aktywnego zakupu Pro.",
        "restoreFailedTitle": "Błąd przywracania",
        "featNutritionTitle": "Spersonalizowany plan żywieniowy",
        "featNutritionDesc": "Indywidualne makro, posiłki i dzienne protokoły",
        "featFitnessTitle": "Spersonalizowany plan treningowy",
        "featFitnessDesc": "4-tygodniowy progresywny program dostosowany do Twojego grafiku",
        "featMentalTitle": "Plan zdrowia psychicznego",
        "featMentalDesc": "Cotygodniowe tematy, redukcja stresu i medytacje",
        "featWomensHealthTitle": "Optymalizacja zdrowia kobiet",
        "featWomensHealthDesc": "Śledzenie cyklu, fazy hormonalne i wsparcie w ciąży",
        "featMensHealthTitle": "Optymalizacja zdrowia mężczyzn",
        "featMensHealthDesc": "Protokoły testosteronu i monitorowanie formy",
        "featProductivityTitle": "Narzędzia produktywności",
        "featProductivityDesc": "Stoper do pracy głębokiej i planowanie dnia",
        "featHabitsTitle": "Śledzenie nawyków",
        "featHabitsDesc": "Buduj codzienne nawyki i utrzymuj serie",
        "featSleepTitle": "Analiza snu",
        "featSleepDesc": "Protokoły snu i optymalizacja rytmu dobowego",
        "featAiCoachTitle": "Osobisty trener AI",
        "featAiCoachDesc": "Nielimitowane odpowiedzi i doradztwo",
        "featVisionTitle": "Skanowanie posiłków AI",
        "featVisionDesc": "Błyskawicznie skanuj posiłki za pomocą aparatu",
        "featAnalyticsTitle": "Zaawansowana analityka",
        "featAnalyticsDesc": "Głębokie trendy zdrowotne i sprawnościowe"
    },
    "ro": {
        "title": "Bluom Pro",
        "subtitle": "Deblochează-ți întregul potențial",
        "bestValue": "★ CEA MAI BUNĂ VALOARE",
        "alreadyPro": "✦ Ești Pro",
        "alreadyProSub": "Accesul complet este activ. Continuă să optimizezi.",
        "continue": "Continuă",
        "trialHeader": "Cum funcționează perioada de probă gratuită",
        "step1Title": "Astăzi: Începe perioada de probă gratuită",
        "step1Sub": "Acces instant și nelimitat la scanarea meselor cu AI, antrenamente și ciclu hormonal.",
        "step2Title": "Ziua 5: Memento perioadă de probă ({{date}})",
        "step2Sub": "Vei primi o notificare și un email de reamintire că perioada de probă se încheie în curând.",
        "step3Title": "Ziua 7: Sfârșitul perioadei de probă ({{date}})",
        "step3Sub": "Vei fi taxat pentru planul selectat. Anulează oricând din setările magazinului.",
        "annualTitle": "Pro Anual",
        "annualSubWithPrice": "Facturat anual ({{price}})",
        "perYear": "/ an",
        "perMonth": "/ lună",
        "perWeek": "/săpt",
        "monthlyTitle": "Pro Lunar",
        "monthlySubWithPrice": "Acces complet, facturat lunar ({{price}})",
        "lifetimeTitle": "Pro Pe Viață",
        "lifetimeSubWithPrice": "Plătești o singură dată, al tău pentru totdeauna ({{price}})",
        "lifetimePaidOff": "amortizat în 1 an",
        "oneTimePayment": "Plată unică",
        "hideOtherOptions": "Ascunde celelalte opțiuni",
        "seeOtherOptions": "Vezi alte opțiuni",
        "includedInTrial": "Inclus în perioada de probă:",
        "priceCompTitle": "Biologie și minte la nivel maxim pentru mai puțin decât o gustare zilnică",
        "gelato": "Înghețată",
        "pint": "Bere",
        "bluomPro": "Bluom Pro",
        "restoring": "Se restaurează…",
        "restorePurchases": "Restaurează achizițiile",
        "terms": "Termeni",
        "privacy": "Confidențialitate",
        "startTrialAndContinue": "Începe proba gratuită & Continuă",
        "getLifetimeAccess": "Obține acces pe viață",
        "subscribeMonthly": "Abonează-te lunar",
        "noCommitment": "Fără obligații · Anulează oricând din Setări",
        "defaultTrialText": "7 zile de probă gratuită",
        "unavailableTitle": "Indisponibil",
        "unavailableMsg": "Verifică conexiunea la internet și încearcă din nou.",
        "welcomeProTitle": "Bun venit la Pro ✦",
        "welcomeProMsg": "Perioada ta de probă este activă. Acces complet deblocat!",
        "purchaseFailedTitle": "Achiziție eșuată",
        "pleaseTryAgain": "Te rugăm să încerci din nou.",
        "restoredTitle": "Restaurat ✦",
        "restoredMsg": "Accesul Pro a fost restaurat cu succes.",
        "nothingToRestoreTitle": "Nimic de restaurat",
        "nothingToRestoreMsg": "Nu a fost găsită nicio achiziție Pro activă.",
        "restoreFailedTitle": "Restaurare eșuată",
        "featNutritionTitle": "Plan nutrițional personalizat",
        "featNutritionDesc": "Macronutrienți personalizați, mese și protocoale zilnice",
        "featFitnessTitle": "Plan de antrenament personalizat",
        "featFitnessDesc": "Program progresiv de 4 săptămâni adaptat programului tău",
        "featMentalTitle": "Plan de sănătate mintală",
        "featMentalDesc": "Teme săptămânale, protocoale anti-stres și meditații ghidate",
        "featWomensHealthTitle": "Optimizarea sănătății feminine",
        "featWomensHealthDesc": "Urmărirea ciclului, faze hormonale și suport în sarcină",
        "featMensHealthTitle": "Sănătate și vitalitate masculină",
        "featMensHealthDesc": "Protocoale de testosteron și monitorizare a performanței",
        "featProductivityTitle": "Instrumente de productivitate",
        "featProductivityDesc": "Cronometru pentru lucru concentrat și planificator zilnic",
        "featHabitsTitle": "Monitorizare obiceiuri",
        "featHabitsDesc": "Construiește obiceiuri zilnice și menține seria activă",
        "featSleepTitle": "Analiza somnului",
        "featSleepDesc": "Protocoale de somn și optimizarea ritmului circadian",
        "featAiCoachTitle": "Antrenor AI dedicat",
        "featAiCoachDesc": "Răspunsuri și îndrumări personalizate nelimitate",
        "featVisionTitle": "Scanare AI pentru mese",
        "featVisionDesc": "Scanează mesele instantaneu cu camera foto",
        "featAnalyticsTitle": "Analize avansate",
        "featAnalyticsDesc": "Tendințe aprofundate privind sănătatea și performanța"
    },
    "tr": {
        "title": "Bluom Pro",
        "subtitle": "Tam potansiyelinizi ortaya çıkarın",
        "bestValue": "★ EN İYİ DEĞER",
        "alreadyPro": "✦ Pro Üyesisiniz",
        "alreadyProSub": "Tam erişim aktif. Kendinizi geliştirmeye devam edin.",
        "continue": "Devam Et",
        "trialHeader": "Ücretsiz deneme süreniz nasıl çalışır?",
        "step1Title": "Bugün: Ücretsiz Denemenizi Başlatın",
        "step1Sub": "Yapay zeka yemek taramaları, egzersizler, zihinsel sağlık ve döngü takibine anında sınırsız erişim.",
        "step2Title": "5. Gün: Deneme Hatırlatıcısı ({{date}})",
        "step2Sub": "Ücretsiz denemenizin yakında biteceğine dair bildirim ve e-posta alacaksınız.",
        "step3Title": "7. Gün: Deneme Bitişi ({{date}})",
        "step3Sub": "Seçtiğiniz plan faturalandırılır. İstediğiniz zaman Mağaza ayarlarından iptal edebilirsiniz.",
        "annualTitle": "Pro Yıllık",
        "annualSubWithPrice": "Yıllık faturalandırılır ({{price}})",
        "perYear": "/ yıl",
        "perMonth": "/ ay",
        "perWeek": "/hf",
        "monthlyTitle": "Pro Aylık",
        "monthlySubWithPrice": "Tam erişim, aylık faturalandırılır ({{price}})",
        "lifetimeTitle": "Pro Ömür Boyu",
        "lifetimeSubWithPrice": "Bir kez ödeyin, sonsuza kadar sahip olun ({{price}})",
        "lifetimePaidOff": "1 yılda amorti eder",
        "oneTimePayment": "Tek seferlik ödeme",
        "hideOtherOptions": "Diğer Seçenekleri Gizle",
        "seeOtherOptions": "Diğer Seçenekleri Gör",
        "includedInTrial": "Denemenize dahil olanlar:",
        "priceCompTitle": "Günlük bir atıştırmalık fiyatından daha ucuza zirve biyoloji ve zihin",
        "gelato": "Dondurma",
        "pint": "Bira",
        "bluomPro": "Bluom Pro",
        "restoring": "Geri yükleniyor…",
        "restorePurchases": "Satın Alımları Geri Yükle",
        "terms": "Şartlar",
        "privacy": "Gizlilik",
        "startTrialAndContinue": "Ücretsiz Denemeyi Başlat & Devam Et",
        "getLifetimeAccess": "Ömür Boyu Erişim Al",
        "subscribeMonthly": "Aylık Abone Ol",
        "noCommitment": "Taahhüt yok · Ayarlar'dan istediğiniz an iptal edin",
        "defaultTrialText": "7 günlük ücretsiz deneme",
        "unavailableTitle": "Kullanılamıyor",
        "unavailableMsg": "Lütfen internet bağlantınızı kontrol edip tekrar deneyin.",
        "welcomeProTitle": "Pro'ya Hoş Geldiniz ✦",
        "welcomeProMsg": "Denemeniz aktif. Tam erişim açıldı!",
        "purchaseFailedTitle": "Satın alma başarısız",
        "pleaseTryAgain": "Lütfen tekrar deneyin.",
        "restoredTitle": "Geri Yüklendi ✦",
        "restoredMsg": "Pro erişiminiz geri yüklendi.",
        "nothingToRestoreTitle": "Geri yüklenecek bir şey yok",
        "nothingToRestoreMsg": "Aktif bir Pro satın alımı bulunamadı.",
        "restoreFailedTitle": "Geri yükleme başarısız",
        "featNutritionTitle": "Kişiselleştirilmiş Beslenme Planı",
        "featNutritionDesc": "Hedeflerinize özel makrolar, öğünler ve günlük protokoller",
        "featFitnessTitle": "Kişiselleştirilmiş Fitness Planı",
        "featFitnessDesc": "Programınıza göre hazırlanmış 4 haftalık aşamalı antrenman",
        "featMentalTitle": "Zihinsel Sağlık Planı",
        "featMentalDesc": "Haftalık zihniyet temaları, stres protokolleri ve meditasyonlar",
        "featWomensHealthTitle": "Kadın Sağlığı Optimizasyonu",
        "featWomensHealthDesc": "Döngü takibi, hormonal evreler ve hamilelik desteği",
        "featMensHealthTitle": "Erkek Sağlığı ve Performansı",
        "featMensHealthDesc": "Testosteron protokolleri ve erkek performans takibi",
        "featProductivityTitle": "Verimlilik Araçları",
        "featProductivityDesc": "Derin çalışma sayaçları ve günlük planlayıcılar",
        "featHabitsTitle": "Alışkanlık Takipçisi",
        "featHabitsDesc": "Günlük alışkanlıklar edinin ve serilerinizi koruyun",
        "featSleepTitle": "Uyku Analizi",
        "featSleepDesc": "Uyku protokolleri ve sirkadiyen ritim optimizasyonu",
        "featAiCoachTitle": "Özel Yapay Zeka Koçu",
        "featAiCoachDesc": "Sınırsız kişiselleştirilmiş yanıtlar ve rehberlik",
        "featVisionTitle": "Yapay Zeka Yemek Taraması",
        "featVisionDesc": "Kameranızla yemekleri anında tarayın",
        "featAnalyticsTitle": "Gelişmiş Analitik",
        "featAnalyticsDesc": "Kapsamlı sağlık ve performans trendleri"
    },
    "el": {
        "title": "Bluom Pro",
        "subtitle": "Ξεκλειδώστε το πλήρες δυναμικό σας",
        "bestValue": "★ ΚΑΛΥΤΕΡΗ ΕΠΙΛΟΓΗ",
        "alreadyPro": "✦ Είστε Pro",
        "alreadyProSub": "Η πλήρης πρόσβαση είναι ενεργή. Συνεχίστε τη βελτιστοποίηση.",
        "continue": "Συνέχεια",
        "trialHeader": "Πώς λειτουργεί η δωρεάν δοκιμή σας",
        "step1Title": "Σήμερα: Ξεκινήστε τη δωρεάν δοκιμή",
        "step1Sub": "Άμεση απεριόριστη πρόσβαση σε σάρωση γευμάτων AI, προπονήσεις και παρακολούθηση κύκλου.",
        "step2Title": "Ημέρα 5: Υπενθύμιση δοκιμής ({{date}})",
        "step2Sub": "Θα λάβετε ειδοποίηση και email ότι η δωρεάν δοκιμή σας ολοκληρώνεται σύντομα.",
        "step3Title": "Ημέρα 7: Λήξη δοκιμής ({{date}})",
        "step3Sub": "Θα χρεωθείτε για το επιλεγμένο πρόγραμμα. Ακυρώστε οποτεδήποτε από τις ρυθμίσεις του Store.",
        "annualTitle": "Pro Ετήσιο",
        "annualSubWithPrice": "Χρέωση ετησίως ({{price}})",
        "perYear": "/ έτος",
        "perMonth": "/ μήνα",
        "perWeek": "/εβδ",
        "monthlyTitle": "Pro Μηνιαίο",
        "monthlySubWithPrice": "Πλήρης πρόσβαση, χρέωση μηνιαίως ({{price}})",
        "lifetimeTitle": "Pro Εφ' όρου Ζωής",
        "lifetimeSubWithPrice": "Πληρώστε μία φορά, δικό σας για πάντα ({{price}})",
        "lifetimePaidOff": "απόσβεση σε 1 έτος",
        "oneTimePayment": "Εφάπαξ πληρωμή",
        "hideOtherOptions": "Απόκρυψη άλλων επιλογών",
        "seeOtherOptions": "Δείτε άλλες επιλογές",
        "includedInTrial": "Περιλαμβάνεται στη δοκιμή σας:",
        "priceCompTitle": "Κορυφαία βιολογία και πνεύμα για λιγότερο από ένα καθημερινό κέρασμα",
        "gelato": "Παγωτό",
        "pint": "Μπύρα",
        "bluomPro": "Bluom Pro",
        "restoring": "Επαναφορά…",
        "restorePurchases": "Επαναφορά αγορών",
        "terms": "Όροι",
        "privacy": "Απόρρητο",
        "startTrialAndContinue": "Έναρξη δωρεάν δοκιμής & Συνέχεια",
        "getLifetimeAccess": "Απόκτηση πρόσβασης εφ' όρου ζωής",
        "subscribeMonthly": "Μηνιαία συνδρομή",
        "noCommitment": "Χωρίς δέσμευση · Ακύρωση ανά πάσα στιγμή στις Ρυθμίσεις",
        "defaultTrialText": "7 ημέρες δωρεάν δοκιμή",
        "unavailableTitle": "Μη διαθέσιμο",
        "unavailableMsg": "Ελέγξτε τη σύνδεσή σας και δοκιμάστε ξανά.",
        "welcomeProTitle": "Καλώς ήρθατε στο Pro ✦",
        "welcomeProMsg": "Η δοκιμή σας είναι ενεργή. Όλες οι λειτουργίες ξεκλειδώθηκαν!",
        "purchaseFailedTitle": "Η αγορά απέτυχε",
        "pleaseTryAgain": "Παρακαλώ δοκιμάστε ξανά.",
        "restoredTitle": "Επαναφέρθηκε ✦",
        "restoredMsg": "Η πρόσβασή σας στο Pro αποκαταστάθηκε.",
        "nothingToRestoreTitle": "Δεν βρέθηκε αγορά",
        "nothingToRestoreMsg": "Δεν βρέθηκε ενεργή αγορά Pro.",
        "restoreFailedTitle": "Η επαναφορά απέτυχε",
        "featNutritionTitle": "Εξατομικευμένο διατροφικό πρόγραμμα",
        "featNutritionDesc": "Προσαρμοσμένα μάκρο, γεύματα και καθημερινά πρωτόκολλα",
        "featFitnessTitle": "Εξατομικευμένο πλάνο προπόνησης",
        "featFitnessDesc": "Προοδευτικό πρόγραμμα 4 εβδομάδων προσαρμοσμένο στις ανάγκες σας",
        "featMentalTitle": "Πρόγραμμα ψυχικής υγείας",
        "featMentalDesc": "Εβδομαδιαία θέματα, πρωτόκολλα κατά του στρες και διαλογισμοί",
        "featWomensHealthTitle": "Βελτιστοποίηση γυναικείας υγείας",
        "featWomensHealthDesc": "Παρακολούθηση κύκλου, ορμονικές φάσεις και υποστήριξη εγκυμοσύνης",
        "featMensHealthTitle": "Ανδρική υγεία & απόδοση",
        "featMensHealthDesc": "Πρωτόκολλα τεστοστερόνης και παρακολούθηση απόδοσης",
        "featProductivityTitle": "Εργαλεία παραγωγικότητας",
        "featProductivityDesc": "Χρονόμετρα βαθιάς εστίασης και καθημερινός προγραμματισμός",
        "featHabitsTitle": "Παρακολούθηση συνηθειών",
        "featHabitsDesc": "Χτίστε καθημερινές συνήθειες και διατηρήστε το σερί σας",
        "featSleepTitle": "Ανάλυση ύπνου",
        "featSleepDesc": "Πρωτόκολλα ύπνου και βελτιστοποίηση κιρκάδιου ρυθμού",
        "featAiCoachTitle": "Προσωπικός AI Coach",
        "featAiCoachDesc": "Απεριόριστες εξατομικευμένες απαντήσεις και καθοδήγηση",
        "featVisionTitle": "AI Σάρωση Γευμάτων",
        "featVisionDesc": "Σαρώστε τα γεύματά σας άμεσα με την κάμερα",
        "featAnalyticsTitle": "Προηγμένη αναλυτική",
        "featAnalyticsDesc": "Λεπτομερείς τάσεις υγείας και φυσικής κατάστασης"
    },
    "bg": {
        "title": "Bluom Pro",
        "subtitle": "Разгърнете пълния си потенциал",
        "bestValue": "★ НАЙ-ДОБРА ЦЕНА",
        "alreadyPro": "✦ Вие сте Pro",
        "alreadyProSub": "Пълният достъп е активен. Продължавайте да оптимизирате.",
        "continue": "Напред",
        "trialHeader": "Как работи безплатният пробен период",
        "step1Title": "Днес: Започнете безплатния пробен период",
        "step1Sub": "Незабавен неограничен достъп до AI сканиране на хранения, тренировки и цикъл.",
        "step2Title": "Ден 5: Напомняне за пробния период ({{date}})",
        "step2Sub": "Ще получите известие и имейл, че пробният ви период изтича скоро.",
        "step3Title": "Ден 7: Край на пробния период ({{date}})",
        "step3Sub": "Ще бъдете таксувани за избрания план. Анулирайте по всяко време в настройките на магазина.",
        "annualTitle": "Pro Годишен",
        "annualSubWithPrice": "Таксува се годишно ({{price}})",
        "perYear": "/ год",
        "perMonth": "/ мес",
        "perWeek": "/седм",
        "monthlyTitle": "Pro Месечен",
        "monthlySubWithPrice": "Пълен достъп, таксуван месечно ({{price}})",
        "lifetimeTitle": "Pro Доживотен",
        "lifetimeSubWithPrice": "Платете веднъж, притежавайте завинаги ({{price}})",
        "lifetimePaidOff": "изплаща се за 1 година",
        "oneTimePayment": "Еднократно плащане",
        "hideOtherOptions": "Скриване на други опции",
        "seeOtherOptions": "Вижте други опции",
        "includedInTrial": "Включено в пробния период:",
        "priceCompTitle": "Върхова биология и ум за по-малко от цената на ежедневно лакомство",
        "gelato": "Сладолед",
        "pint": "Бира",
        "bluomPro": "Bluom Pro",
        "restoring": "Възстановяване…",
        "restorePurchases": "Възстановяване на покупки",
        "terms": "Условия",
        "privacy": "Поверителност",
        "startTrialAndContinue": "Стартирайте безплатен тест & Напред",
        "getLifetimeAccess": "Вземете доживотен достъп",
        "subscribeMonthly": "Месечен абонамент",
        "noCommitment": "Без обвързване · Анулирайте по всяко време в Настройки",
        "defaultTrialText": "7 дни безплатен пробен период",
        "unavailableTitle": "Недостъпно",
        "unavailableMsg": "Моля, проверете връзката си с интернет и опитайте отново.",
        "welcomeProTitle": "Добре дошли в Pro ✦",
        "welcomeProMsg": "Пробният ви период е активен. Пълният достъп е отключен!",
        "purchaseFailedTitle": "Покупката е неуспешна",
        "pleaseTryAgain": "Моля, опитайте отново.",
        "restoredTitle": "Възстановено ✦",
        "restoredMsg": "Вашият Pro достъп беше успешно възстановен.",
        "nothingToRestoreTitle": "Няма данни за възстановяване",
        "nothingToRestoreMsg": "Не беше намерена активна Pro покупка.",
        "restoreFailedTitle": "Възстановяването е неуспешно",
        "featNutritionTitle": "Персонализиран хранителен план",
        "featNutritionDesc": "Персонализирани макроси, хранения и ежедневни протоколи",
        "featFitnessTitle": "Персонализиран фитнес план",
        "featFitnessDesc": "4-седмична прогресивна програма съобразена с вашия график",
        "featMentalTitle": "План за ментално здраве",
        "featMentalDesc": "Седмични теми, протоколи срещу стрес и медитации",
        "featWomensHealthTitle": "Женско здраве и хормони",
        "featWomensHealthDesc": "Проследяване на цикъла, хормонални фази и подкрепа при бременност",
        "featMensHealthTitle": "Мъжко здраве и тонус",
        "featMensHealthDesc": "Тестостеронови протоколи и проследяване на физическата форма",
        "featProductivityTitle": "Инструменти за продуктивност",
        "featProductivityDesc": "Таймери за дълбока работа и дневно планиране",
        "featHabitsTitle": "Проследяване на навици",
        "featHabitsDesc": "Изграждайте ежедневни навици и поддържайте серията си",
        "featSleepTitle": "Анализ на съня",
        "featSleepDesc": "Протоколи за сън и оптимизация на циркадния ритъм",
        "featAiCoachTitle": "Личен AI треньор",
        "featAiCoachDesc": "Неограничени персонализирани отговори и съвети",
        "featVisionTitle": "AI сканиране на храни",
        "featVisionDesc": "Сканирайте ястията си незабавно с камерата",
        "featAnalyticsTitle": "Разширена аналитика",
        "featAnalyticsDesc": "Подробни тенденции за здравето и формата ви"
    },
    "hg": {
        "title": "Bluom Pro",
        "subtitle": "Hozza ki a legtöbbet magából",
        "bestValue": "★ LEGJOBB ÉRTÉK",
        "alreadyPro": "✦ Ön Pro tag",
        "alreadyProSub": "A teljes hozzáférés aktív. Folytassa a fejlődést.",
        "continue": "Tovább",
        "trialHeader": "Így működik az ingyenes próbaidőszak",
        "step1Title": "Ma: Indítsa el az ingyenes próbaidőszakot",
        "step1Sub": "Azonnali, korlátlan hozzáférés az AI ételvizsgálatokhoz, edzésekhez és ciklusprotokollokhoz.",
        "step2Title": "5. nap: Próbaidőszak emlékeztető ({{date}})",
        "step2Sub": "Értesítést és e-mailt kap arról, hogy az ingyenes próbaidőszak hamarosan véget ér.",
        "step3Title": "7. nap: A próbaidőszak véget ér ({{date}})",
        "step3Sub": "A kiválasztott csomag díja felszámításra kerül. Bármikor lemondható az áruház beállításaiban.",
        "annualTitle": "Pro Éves",
        "annualSubWithPrice": "Évente számlázva ({{price}})",
        "perYear": "/ év",
        "perMonth": "/ hó",
        "perWeek": "/hét",
        "monthlyTitle": "Pro Havi",
        "monthlySubWithPrice": "Teljes hozzáférés, havonta számlázva ({{price}})",
        "lifetimeTitle": "Pro Örökös",
        "lifetimeSubWithPrice": "Fizessen egyszer, birtokolja örökre ({{price}})",
        "lifetimePaidOff": "1 év alatt megtérül",
        "oneTimePayment": "Egyszeri fizetés",
        "hideOtherOptions": "Egyéb opciók elrejtése",
        "seeOtherOptions": "Egyéb opciók megtekintése",
        "includedInTrial": "A próbaidőszak tartalma:",
        "priceCompTitle": "Csúcsbiológia és elme kevesebbért, mint egy napi kávé vagy édesség",
        "gelato": "Fagylalt",
        "pint": "Sör",
        "bluomPro": "Bluom Pro",
        "restoring": "Visszaállítás…",
        "restorePurchases": "Vásárlások visszaállítása",
        "terms": "Feltételek",
        "privacy": "Adatvédelem",
        "startTrialAndContinue": "Ingyenes próba indítása & Tovább",
        "getLifetimeAccess": "Örökös hozzáférés vásárlása",
        "subscribeMonthly": "Havi előfizetés",
        "noCommitment": "Nincs elköteleződés · Bármikor lemondható a Beállításokban",
        "defaultTrialText": "7 napos ingyenes próbaidőszak",
        "unavailableTitle": "Nem elérhető",
        "unavailableMsg": "Kérjük, ellenőrizze internetkapcsolatát, és próbálja újra.",
        "welcomeProTitle": "Üdvözöljük a Pro-ban ✦",
        "welcomeProMsg": "A próbaidőszak aktív. A teljes hozzáférés feloldva!",
        "purchaseFailedTitle": "Sikertelen vásárlás",
        "pleaseTryAgain": "Kérjük, próbálja újra.",
        "restoredTitle": "Visszaállítva ✦",
        "restoredMsg": "Pro hozzáférése sikeresen visszaállítva.",
        "nothingToRestoreTitle": "Nincs visszaállítható vásárlás",
        "nothingToRestoreMsg": "Nem található aktív Pro vásárlás.",
        "restoreFailedTitle": "Visszaállítás sikertelen",
        "featNutritionTitle": "Személyre szabott étrend",
        "featNutritionDesc": "Egyéni makrók, ételek és napi protokollok céljaihoz igazítva",
        "featFitnessTitle": "Személyre szabott edzésterv",
        "featFitnessDesc": "4 hetes progresszív program az Ön napirendjéhez igazítva",
        "featMentalTitle": "Mentális egészségügyi terv",
        "featMentalDesc": "Heti témák, stresszcsökkentő protokollok és meditációk",
        "featWomensHealthTitle": "Női egészség optimalizálása",
        "featWomensHealthDesc": "Cikluskövetés, hormonális fázisok és terhességi támogatás",
        "featMensHealthTitle": "Férfi egészség & teljesítmény",
        "featMensHealthDesc": "Tesztoszteron protokollok és fizikai teljesítménykövetés",
        "featProductivityTitle": "Produktivitási eszközök",
        "featProductivityDesc": "Mélyfókusz időzítők és napi tervezők",
        "featHabitsTitle": "Szokáskövető",
        "featHabitsDesc": "Építsen szokásokat és tartsa meg sikersorozatait",
        "featSleepTitle": "Alváselemzés",
        "featSleepDesc": "Alvási protokollok és a cirkadián ritmus optimalizálása",
        "featAiCoachTitle": "Dedikált AI edző",
        "featAiCoachDesc": "Korlátlan személyre szabott válasz és tanácsadás",
        "featVisionTitle": "AI Ételvizsgálat",
        "featVisionDesc": "Vizsgálja meg ételeit azonnal a kamerájával",
        "featAnalyticsTitle": "Részletes analitika",
        "featAnalyticsDesc": "Mélyreható egészségügyi és teljesítménytrendek"
    },
    "lt": {
        "title": "Bluom Pro",
        "subtitle": "Atskleiskite visą savo potencialą",
        "bestValue": "★ GERIAUSIA VERTĖ",
        "alreadyPro": "✦ Jūs esate Pro",
        "alreadyProSub": "Pilna prieiga aktyvi. Tęskite tobulėjimą.",
        "continue": "Tęsti",
        "trialHeader": "Kaip veikia nemokamas bandomasis laikotarpis",
        "step1Title": "Šiandien: Pradėkite nemokamą bandomąjį laikotarpį",
        "step1Sub": "Akimirksniu gaukite neribotą prieigą prie AI patiekalų nuskaitymo, treniruočių ir ciklo analizės.",
        "step2Title": "5 diena: Bandomojo laikotarpio priminimas ({{date}})",
        "step2Sub": "Gausite pranešimą ir el. laišką su priminimu, kad bandomasis laikotarpis greitai baigsis.",
        "step3Title": "7 diena: Bandomojo laikotarpio pabaiga ({{date}})",
        "step3Sub": "Bus taikomas pasirinkto plano mokestis. Bet kada atšaukite parduotuvės nustatymuose.",
        "annualTitle": "Pro Metinis",
        "annualSubWithPrice": "Mokama kasmet ({{price}})",
        "perYear": "/ m.",
        "perMonth": "/ mėn.",
        "perWeek": "/sav.",
        "monthlyTitle": "Pro Mėnesinis",
        "monthlySubWithPrice": "Pilna prieiga, mokama kas mėnesį ({{price}})",
        "lifetimeTitle": "Pro Visam Gyvenimui",
        "lifetimeSubWithPrice": "Mokėkite kartą, naudokitės visada ({{price}})",
        "lifetimePaidOff": "atsiperka per 1 metus",
        "oneTimePayment": "Vienkartinis mokėjimas",
        "hideOtherOptions": "Slėpti kitas parinktis",
        "seeOtherOptions": "Rodyti kitas parinktis",
        "includedInTrial": "Įskaičiuota į bandomąjį laikotarpį:",
        "priceCompTitle": "Aukščiausia biologinė forma ir aštrus protas pigiau nei kasdienis desertas",
        "gelato": "Ledai",
        "pint": "Alus",
        "bluomPro": "Bluom Pro",
        "restoring": "Atkuriama…",
        "restorePurchases": "Atkurti pirkinius",
        "terms": "Sąlygos",
        "privacy": "Privatumas",
        "startTrialAndContinue": "Pradėti nemokamą bandymą & Tęsti",
        "getLifetimeAccess": "Gauti prieigą visam gyvenimui",
        "subscribeMonthly": "Užsiprenumeruoti kas mėnesį",
        "noCommitment": "Jokių įsipareigojimų · Bet kada atšaukite Nustatymuose",
        "defaultTrialText": "7 dienų nemokamas bandomasis laikotarpis",
        "unavailableTitle": "Nepasiekiamas",
        "unavailableMsg": "Patikrinkite interneto ryšį ir bandykite dar kartą.",
        "welcomeProTitle": "Sveiki atvykę į Pro ✦",
        "welcomeProMsg": "Bandomasis laikotarpis aktyvus. Pilna prieiga atrakinta!",
        "purchaseFailedTitle": "Pirkimas nepavyko",
        "pleaseTryAgain": "Bandykite dar kartą.",
        "restoredTitle": "Atkurta ✦",
        "restoredMsg": "Jūsų Pro prieiga sėkmingai atkurta.",
        "nothingToRestoreTitle": "Nėra ką atkurti",
        "nothingToRestoreMsg": "Nerasta aktyvių Pro pirkinių.",
        "restoreFailedTitle": "Atkurti nepavyko",
        "featNutritionTitle": "Personalizuotas mitybos planas",
        "featNutritionDesc": "Pritaikyti makroelementai, patiekalai ir kasdieniai protokolai",
        "featFitnessTitle": "Personalizuotas treniruočių planas",
        "featFitnessDesc": "4 savaičių progresyvi programa, pritaikyta prie jūsų tvarkaraščio",
        "featMentalTitle": "Emocinės sveikatos planas",
        "featMentalDesc": "Savaitinės temos, streso mažinimo protokolai ir meditacijos",
        "featWomensHealthTitle": "Moterų sveikatos optimizavimas",
        "featWomensHealthDesc": "Ciklo stebėjimas, hormoninės fazės ir nėštumo palaikymas",
        "featMensHealthTitle": "Vyrų sveikata ir ištvermė",
        "featMensHealthDesc": "Testosterono protokolai ir fizinės formos sekimas",
        "featProductivityTitle": "Produktyvumo įrankiai",
        "featProductivityDesc": "Gilaus darbo laikmačiai ir dienotvarkės planuokliai",
        "featHabitsTitle": "Įpročių seklys",
        "featHabitsDesc": "Kurkite kasdienius įpročius ir išlaikykite serijas",
        "featSleepTitle": "Miego analizė",
        "featSleepDesc": "Miego protokolai ir paros ritmo optimizavimas",
        "featAiCoachTitle": "Asmeninis AI treneris",
        "featAiCoachDesc": "Neriboti asmeniniai atsakymai ir patarimai",
        "featVisionTitle": "AI Maisto nuskaitymas",
        "featVisionDesc": "Nuskenuokite patiekalus kamera akimirksniu",
        "featAnalyticsTitle": "Išsami analitika",
        "featAnalyticsDesc": "Gilios sveikatos ir fizinės formos tendencijos"
    },
    "lv": {
        "title": "Bluom Pro",
        "subtitle": "Atveriet savu pilno potenciālu",
        "bestValue": "★ LABĀKĀ VĒRTĪBA",
        "alreadyPro": "✦ Jūs esat Pro",
        "alreadyProSub": "Pilna piekļuve ir aktīva. Turpiniet pilnveidoties.",
        "continue": "Turpināt",
        "trialHeader": "Kā darbojas bezmaksas izmēģinājums",
        "step1Title": "Šodien: Sāciet bezmaksas izmēģinājuma periodu",
        "step1Sub": "Tūlītēja neierobežota piekļuve AI ēdienu skenēšanai, treniņiem un cikla analīzei.",
        "step2Title": "5. diena: Izmēģinājuma atgādinājums ({{date}})",
        "step2Sub": "Saņemsiet paziņojumu un e-pastu, atgādinot, ka izmēģinājuma periods drīz beigsies.",
        "step3Title": "7. diena: Izmēģinājuma beigas ({{date}})",
        "step3Sub": "Tiks iekasēta maksa par izvēlēto plānu. Jebkurā laikā atceliet veikala iestatījumos.",
        "annualTitle": "Pro Gada",
        "annualSubWithPrice": "Rēķins reizi gadā ({{price}})",
        "perYear": "/ gadā",
        "perMonth": "/ mēnesī",
        "perWeek": "/ned.",
        "monthlyTitle": "Pro Mēneša",
        "monthlySubWithPrice": "Pilna piekļuve, rēķins katru mēnesi ({{price}})",
        "lifetimeTitle": "Pro Mūža",
        "lifetimeSubWithPrice": "Maksājiet vienreiz, lietojiet mūžīgi ({{price}})",
        "lifetimePaidOff": "atmaksājas 1 gada laikā",
        "oneTimePayment": "Vienreizējs maksājums",
        "hideOtherOptions": "Slēpt citas iespējas",
        "seeOtherOptions": "Rādīt citas iespējas",
        "includedInTrial": "Iekļauts izmēģinājumā:",
        "priceCompTitle": "Maksimāla bioloģiskā forma un asums lētāk par ikdienas kārumu",
        "gelato": "Saldējums",
        "pint": "Alus",
        "bluomPro": "Bluom Pro",
        "restoring": "Atjauno…",
        "restorePurchases": "Atjaunot pirkumus",
        "terms": "Noteikumi",
        "privacy": "Privātums",
        "startTrialAndContinue": "Sākt bezmaksas izmēģinājumu & Turpināt",
        "getLifetimeAccess": "Iegūt mūža piekļuvi",
        "subscribeMonthly": "Abonēt katru mēnesi",
        "noCommitment": "Bez saistībām · Atceliet jebkurā laikā Iestatījumos",
        "defaultTrialText": "7 dienu bezmaksas izmēģinājums",
        "unavailableTitle": "Nav pieejams",
        "unavailableMsg": "Lūdzu, pārbaudiet interneta savienojumu un mēģiniet vēlreiz.",
        "welcomeProTitle": "Laipni lūdzam Pro ✦",
        "welcomeProMsg": "Izmēģinājums ir aktīvs. Pilna piekļuve ir atbloķēta!",
        "purchaseFailedTitle": "Pirkums neizdevās",
        "pleaseTryAgain": "Lūdzu, mēģiniet vēlreiz.",
        "restoredTitle": "Atjaunots ✦",
        "restoredMsg": "Jūsu Pro piekļuve ir veiksmīgi atjaunota.",
        "nothingToRestoreTitle": "Nav ko atjaunot",
        "nothingToRestoreMsg": "Aktīvs Pro pirkums netika atrasts.",
        "restoreFailedTitle": "Atjaunošana neizdevās",
        "featNutritionTitle": "Personalizēts uztura plāns",
        "featNutritionDesc": "Pielāgoti makroelementi, maltītes un ikdienas protokoli",
        "featFitnessTitle": "Personalizēts treniņu plāns",
        "featFitnessDesc": "4 nedēļu progresīva programma, kas pielāgota jūsu grafikam",
        "featMentalTitle": "Mentālās veselības plāns",
        "featMentalDesc": "Iknedēļas tēmas, stresa mazināšanas protokoli un meditācijas",
        "featWomensHealthTitle": "Sieviešu veselības optimizācija",
        "featWomensHealthDesc": "Cikla izsekošana, hormonālie posmi un grūtniecības atbalsts",
        "featMensHealthTitle": "Vīriešu veselība & spēks",
        "featMensHealthDesc": "Testosterona protokoli un fiziskās formas analīze",
        "featProductivityTitle": "Produktivitātes rīki",
        "featProductivityDesc": "Dziļā darba taimeri un ikdienas plānotāji",
        "featHabitsTitle": "Ieradumu sekotājs",
        "featHabitsDesc": "Veidojiet ikdienas ieradumus un saglabājiet sērijas",
        "featSleepTitle": "Miega analīze",
        "featSleepDesc": "Miega protokoli un diennakts ritma optimizācija",
        "featAiCoachTitle": "Personīgais AI treneris",
        "featAiCoachDesc": "Neierobežotas personalizētas atbildes un padomi",
        "featVisionTitle": "AI Ēdienu skenēšana",
        "featVisionDesc": "Skenējiet ēdienreizes acumirklī ar kameru",
        "featAnalyticsTitle": "Padziļināta analītika",
        "featAnalyticsDesc": "Dziļas veselības un fiziskās formas tendences"
    }
}

count_updated = 0

for lang_code, translations in TRANSLATIONS.items():
    file_path = os.path.join(LOCALES_DIR, lang_code, "translation.json")
    if not os.path.exists(file_path):
        print(f"Skipping missing: {file_path}")
        continue
    
    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    if "premium" not in data or not isinstance(data["premium"], dict):
        data["premium"] = {}
    
    # Merge translations into premium namespace
    for key, value in translations.items():
        data["premium"][key] = value
    
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=4)
    
    count_updated += 1
    print(f"[OK] Updated {lang_code} with {len(translations)} premium keys.")

print(f"\nDone! Successfully updated {count_updated} translation files.")
